import {type Course, makeMcqBuilder, makeQueryBuilder} from "./course-types";

const basic = makeMcqBuilder("Basics");
const concept = makeMcqBuilder("Concepts");
const query = makeQueryBuilder("sql");

const ROUND_ONE_STEPS = [
  basic(
    1,
    6,
    "Cassandra's data model is best described as which style?",
    ["Wide-column", "Document store", "Key-value only", "Graph"],
    0,
    "Cassandra organizes data into wide-column tables grouped by partition.",
    "It is neither a document store nor a pure key-value store.",
  ),
  basic(
    2,
    6,
    "Which key decides which node stores a row in Cassandra?",
    ["Partition key", "Foreign key", "Primary index", "Shard code"],
    0,
    "The partition key is hashed to determine which node owns that data.",
    "Think about what spreads data across the cluster.",
  ),
  basic(
    3,
    6,
    "What must you create before creating tables in Cassandra?",
    ["A keyspace", "A schema file", "A cluster license", "A view"],
    0,
    "A keyspace is Cassandra's top-level container, similar to a database in SQL.",
    "Tables always belong to one of these.",
  ),
  basic(
    4,
    6,
    "What is Cassandra's query language called?",
    ["CQL", "PL/SQL", "T-SQL", "GQL"],
    0,
    "CQL (Cassandra Query Language) looks similar to SQL but works differently underneath.",
    "The C stands for the database's own name.",
  ),
  basic(
    5,
    6,
    "Which property is Cassandra especially known for across many nodes?",
    ["High availability", "Strict foreign keys", "Single point of failure", "In-memory only"],
    0,
    "Cassandra is designed to keep serving requests even when some nodes fail.",
    "Think about uptime across a distributed cluster.",
  ),
  basic(
    6,
    6,
    "Which scaling approach does Cassandra use as data grows?",
    ["Horizontal scaling", "Vertical scaling only", "Manual sharding by hand", "No scaling needed"],
    0,
    "Cassandra scales out by adding more nodes rather than growing one server.",
    "The clue is adding more machines instead of a bigger machine.",
  ),
  query(
    "tables",
    "Tables & Data",
    1,
    3,
    "Create a keyspace named school_ks with SimpleStrategy replication and a replication factor of 3.",
    "CREATE KEYSPACE school_ks WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 3};",
    ["CREATE KEYSPACE school_ks WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 3};"],
    "Every keyspace needs a replication strategy and factor declared when it is created.",
    "Use CREATE KEYSPACE ... WITH replication = {...}.",
  ),
  query(
    "tables",
    "Tables & Data",
    2,
    3,
    "Create a table named students with id UUID as the primary key, name TEXT, and age INT.",
    "CREATE TABLE students (id UUID PRIMARY KEY, name TEXT, age INT);",
    ["CREATE TABLE students (id UUID PRIMARY KEY, name TEXT, age INT);"],
    "A simple single-column primary key also acts as the partition key.",
    "Use CREATE TABLE students (id UUID PRIMARY KEY, ...).",
  ),
  query(
    "tables",
    "Tables & Data",
    3,
    3,
    "Insert a student with id 11111111-1111-1111-1111-111111111111, name 'Asha', and age 18.",
    "INSERT INTO students (id, name, age) VALUES (11111111-1111-1111-1111-111111111111, 'Asha', 18);",
    ["INSERT INTO students (id, name, age) VALUES (11111111-1111-1111-1111-111111111111, 'Asha', 18);"],
    "CQL UUID literals are written without quotes.",
    "Use INSERT INTO students (id, name, age) VALUES (...).",
  ),
  query(
    "filtering",
    "Filtering",
    1,
    3,
    "Select every column for the student whose id is 11111111-1111-1111-1111-111111111111.",
    "SELECT * FROM students WHERE id = 11111111-1111-1111-1111-111111111111;",
    ["SELECT * FROM students WHERE id = 11111111-1111-1111-1111-111111111111;"],
    "CQL queries always filter on the partition key for an efficient read.",
    "Use WHERE id = 11111111-1111-1111-1111-111111111111.",
  ),
  query(
    "filtering",
    "Filtering",
    2,
    3,
    "Update the age of the student with id 11111111-1111-1111-1111-111111111111 to 19.",
    "UPDATE students SET age = 19 WHERE id = 11111111-1111-1111-1111-111111111111;",
    ["UPDATE students SET age = 19 WHERE id = 11111111-1111-1111-1111-111111111111;"],
    "UPDATE ... SET ... WHERE works similarly to standard SQL.",
    "Target the row by its partition key in WHERE.",
  ),
  query(
    "filtering",
    "Filtering",
    3,
    3,
    "Delete the student with id 11111111-1111-1111-1111-111111111111.",
    "DELETE FROM students WHERE id = 11111111-1111-1111-1111-111111111111;",
    ["DELETE FROM students WHERE id = 11111111-1111-1111-1111-111111111111;"],
    "DELETE FROM also needs the partition key in its WHERE clause.",
    "Use DELETE FROM students WHERE id = ....",
  ),
];

const ROUND_TWO_STEPS = [
  concept(
    1,
    6,
    "Which key orders the rows stored within a single partition?",
    ["Clustering column", "Partition key", "Foreign key", "Index key"],
    0,
    "Clustering columns decide the on-disk order of rows that share a partition key.",
    "It is the second part of a composite primary key.",
  ),
  concept(
    2,
    6,
    "Which clause lets you filter on a non-indexed column, at a performance cost?",
    ["ALLOW FILTERING", "FORCE SCAN", "IGNORE INDEX", "SLOW MODE"],
    0,
    "ALLOW FILTERING permits a query Cassandra would otherwise reject as inefficient.",
    "Cassandra requires you to explicitly opt in to this kind of scan.",
  ),
  concept(
    3,
    6,
    "Which setting controls how many replicas must respond to a read or write?",
    ["Consistency level", "Isolation level", "Durability level", "Cache level"],
    0,
    "Consistency level tunes the tradeoff between speed and up-to-date reads.",
    "It is set per query, such as ONE or QUORUM.",
  ),
  concept(
    4,
    6,
    "Which clause makes a written row automatically expire after a duration?",
    ["USING TTL", "EXPIRE AFTER", "AUTO DELETE", "SET LIFETIME"],
    0,
    "USING TTL sets a time-to-live in seconds for the row being written.",
    "TTL stands for time to live.",
  ),
  concept(
    5,
    6,
    "Which statement groups several CQL writes to run together?",
    ["BATCH", "TRANSACTION", "GROUP", "BULK"],
    0,
    "BEGIN BATCH ... APPLY BATCH wraps multiple writes into one request.",
    "It is bounded by BEGIN and APPLY keywords.",
  ),
  concept(
    6,
    6,
    "Cassandra tables typically avoid which relational feature because of its cost across nodes?",
    ["JOINs", "Indexes", "Primary keys", "Inserts"],
    0,
    "Cassandra favors designing tables around queries instead of joining across tables.",
    "Think about the SQL feature that needs data from two tables at once.",
  ),
  query(
    "clustering",
    "Clustering & Filtering",
    1,
    3,
    "Create a table named posts with user_id UUID and post_id TIMEUUID, body TEXT, using user_id as the partition key and post_id as the clustering column.",
    "CREATE TABLE posts (user_id UUID, post_id TIMEUUID, body TEXT, PRIMARY KEY (user_id, post_id));",
    ["CREATE TABLE posts (user_id UUID, post_id TIMEUUID, body TEXT, PRIMARY KEY (user_id, post_id));"],
    "A composite PRIMARY KEY (partition_key, clustering_column) sets both roles at once.",
    "Use PRIMARY KEY (user_id, post_id).",
  ),
  query(
    "clustering",
    "Clustering & Filtering",
    2,
    3,
    "Select every post for the user with user_id 11111111-1111-1111-1111-111111111111, newest first.",
    "SELECT * FROM posts WHERE user_id = 11111111-1111-1111-1111-111111111111 ORDER BY post_id DESC;",
    ["SELECT * FROM posts WHERE user_id = 11111111-1111-1111-1111-111111111111 ORDER BY post_id DESC;"],
    "ORDER BY in CQL can only sort by the clustering column, within one partition.",
    "Filter by user_id, then ORDER BY post_id DESC.",
  ),
  query(
    "clustering",
    "Clustering & Filtering",
    3,
    3,
    "Select students older than 18, allowing filtering on the non-indexed age column.",
    "SELECT * FROM students WHERE age > 18 ALLOW FILTERING;",
    ["SELECT * FROM students WHERE age > 18 ALLOW FILTERING;"],
    "ALLOW FILTERING is required whenever the WHERE clause is not on an indexed column.",
    "Add ALLOW FILTERING at the end of the statement.",
  ),
  query(
    "ttl",
    "TTL & Batches",
    1,
    3,
    "Insert a session with id 'abc' and user 'Asha' that expires after 3600 seconds.",
    "INSERT INTO sessions (id, user) VALUES ('abc', 'Asha') USING TTL 3600;",
    ["INSERT INTO sessions (id, user) VALUES ('abc', 'Asha') USING TTL 3600;"],
    "USING TTL sets how many seconds until the row is automatically removed.",
    "Add USING TTL 3600 after the VALUES list.",
  ),
  query(
    "ttl",
    "TTL & Batches",
    2,
    3,
    "Create an index named idx_age on the age column of students.",
    "CREATE INDEX idx_age ON students (age);",
    ["CREATE INDEX idx_age ON students (age);"],
    "A secondary index lets you filter on age without needing ALLOW FILTERING.",
    "Use CREATE INDEX idx_age ON students (age).",
  ),
  query(
    "ttl",
    "TTL & Batches",
    3,
    3,
    "In one BATCH, insert a student with id 11111111-1111-1111-1111-111111111111 named 'Asha' and update the student with id 22222222-2222-2222-2222-222222222222 to set age to 20.",
    "BEGIN BATCH INSERT INTO students (id, name) VALUES (11111111-1111-1111-1111-111111111111, 'Asha'); UPDATE students SET age = 20 WHERE id = 22222222-2222-2222-2222-222222222222; APPLY BATCH;",
    [
      "BEGIN BATCH INSERT INTO students (id, name) VALUES (11111111-1111-1111-1111-111111111111, 'Asha'); UPDATE students SET age = 20 WHERE id = 22222222-2222-2222-2222-222222222222; APPLY BATCH;",
    ],
    "BEGIN BATCH ... APPLY BATCH wraps several statements so they apply together.",
    "Start with BEGIN BATCH, list both statements, then end with APPLY BATCH.",
  ),
];

export const CASSANDRA_COURSE: Course = {
  rounds: [
    {
      number: 1,
      title: "Round 1",
      summary: "6 basics questions and 6 query drills covering keyspaces, tables, and filtering.",
      topics: ["Basics", "Tables & Data", "Filtering"],
      steps: ROUND_ONE_STEPS,
    },
    {
      number: 2,
      title: "Round 2",
      summary: "6 concept checks and 6 harder query drills covering clustering, TTLs, indexes, and batches.",
      topics: ["Concepts", "Clustering & Filtering", "TTL & Batches"],
      steps: ROUND_TWO_STEPS,
    },
  ],
};
