import {type Course, makeMcqBuilder, makeQueryBuilder} from "./course-types";

const basic = makeMcqBuilder("Basics");
const concept = makeMcqBuilder("Concepts");
const query = makeQueryBuilder("code");

const ROUND_ONE_STEPS = [
  basic(
    1,
    6,
    "What is a single Firestore record called?",
    ["Document", "Row", "Tuple", "Record"],
    0,
    "Firestore stores data as documents, similar to other NoSQL document databases.",
    "It is the same term MongoDB uses for one record.",
  ),
  basic(
    2,
    6,
    "What is a group of Firestore documents called?",
    ["Collection", "Table", "Bucket", "Schema"],
    0,
    "Documents live inside collections, which you reference by name.",
    "It is the word used instead of 'table'.",
  ),
  basic(
    3,
    6,
    "Which Firebase product handles user sign-up and login?",
    ["Firebase Authentication", "Cloud Functions", "Firebase Hosting", "Cloud Storage"],
    0,
    "Firebase Authentication manages accounts, sessions, and sign-in providers.",
    "Its name says exactly what it does.",
  ),
  basic(
    4,
    6,
    "Which Firestore feature pushes data changes to listeners instantly?",
    ["Realtime listeners", "Manual polling only", "Batch export", "Scheduled sync"],
    0,
    "Firestore can notify your app the moment matching data changes, without polling.",
    "Think about live updates instead of checking again and again.",
  ),
  basic(
    5,
    6,
    "Which method creates a new document with an auto-generated ID?",
    ["add()", "insert()", "create()", "push()"],
    0,
    "add() lets Firestore generate a unique document ID for you.",
    "It is called on a collection reference.",
  ),
  basic(
    6,
    6,
    "Which method fetches a document or query's data once?",
    ["get()", "fetch()", "read()", "load()"],
    0,
    "get() returns the current data a single time, unlike a realtime listener.",
    "It is the simplest, most direct read method.",
  ),
  query(
    "crud",
    "CRUD",
    1,
    3,
    "Add a new document to the students collection with name 'Asha' and age 18, letting Firestore generate the ID.",
    "db.collection('students').add({name: 'Asha', age: 18});",
    ["db.collection('students').add({name: 'Asha', age: 18});"],
    "add() creates a new document and assigns it a random ID automatically.",
    "Call .collection('students').add({...}).",
  ),
  query(
    "crud",
    "CRUD",
    2,
    3,
    "Set the document with ID '1' in the students collection to name 'Asha' and age 18.",
    "db.collection('students').doc('1').set({name: 'Asha', age: 18});",
    ["db.collection('students').doc('1').set({name: 'Asha', age: 18});"],
    "doc('1') targets a specific document by ID, and set() writes its full data.",
    "Chain .doc('1').set({...}) after the collection reference.",
  ),
  query(
    "crud",
    "CRUD",
    3,
    3,
    "Update the document with ID '1' in students so its age becomes 19.",
    "db.collection('students').doc('1').update({age: 19});",
    ["db.collection('students').doc('1').update({age: 19});"],
    "update() only changes the fields you pass, leaving the rest untouched.",
    "Chain .doc('1').update({age: 19}).",
  ),
  query(
    "queries",
    "Queries",
    1,
    3,
    "Get every document in the students collection.",
    "db.collection('students').get();",
    ["db.collection('students').get();"],
    "Calling get() on a collection reference returns every document in it.",
    "Call .collection('students').get().",
  ),
  query(
    "queries",
    "Queries",
    2,
    3,
    "Get students where age is greater than 18.",
    "db.collection('students').where('age', '>', 18).get();",
    ["db.collection('students').where('age', '>', 18).get();"],
    "where() takes a field, an operator, and a value to compare against.",
    "Chain .where('age', '>', 18) before .get().",
  ),
  query(
    "queries",
    "Queries",
    3,
    3,
    "Delete the document with ID '1' from the students collection.",
    "db.collection('students').doc('1').delete();",
    ["db.collection('students').doc('1').delete();"],
    "delete() removes the targeted document entirely.",
    "Chain .doc('1').delete().",
  ),
];

const ROUND_TWO_STEPS = [
  concept(
    1,
    6,
    "Which method keeps a query's results updated in real time?",
    ["onSnapshot()", "get()", "watch()", "poll()"],
    0,
    "onSnapshot() calls your callback again every time matching data changes.",
    "Its name describes receiving a fresh snapshot each time.",
  ),
  concept(
    2,
    6,
    "Which Firestore feature groups documents inside another document?",
    ["Subcollections", "Foreign keys", "Joins", "Views"],
    0,
    "A subcollection lives inside a specific document, like items inside one order.",
    "Firestore has no joins, so nesting is done this way instead.",
  ),
  concept(
    3,
    6,
    "Where do you write rules that control who can read or write documents?",
    ["Security rules", "IAM policies", ".htaccess", "CORS config"],
    0,
    "Firestore security rules are written separately and enforced on every request.",
    "It is a Firebase-specific concept, not a general web server setting.",
  ),
  concept(
    4,
    6,
    "Which method groups several writes so they all succeed or fail together?",
    ["batch()", "transaction() only", "bulkWrite()", "group()"],
    0,
    "batch() lets you queue multiple writes and commit them as one atomic unit.",
    "The word suggests bundling several operations together.",
  ),
  concept(
    5,
    6,
    "Which method limits how many documents a query returns?",
    ["limit()", "take()", "top()", "cap()"],
    0,
    "limit() caps the number of documents a query returns, similar to SQL's LIMIT.",
    "It shares its name with the SQL clause it resembles.",
  ),
  concept(
    6,
    6,
    "Which method sorts query results by a field?",
    ["orderBy()", "sort()", "rank()", "arrange()"],
    0,
    "orderBy() takes a field name and an optional direction to sort results.",
    "It reads naturally: order by a field.",
  ),
  query(
    "live",
    "Live Queries",
    1,
    3,
    "Listen for realtime updates on the students collection, logging each snapshot with a callback named snapshot.",
    "db.collection('students').onSnapshot(snapshot => console.log(snapshot));",
    ["db.collection('students').onSnapshot(snapshot => console.log(snapshot));"],
    "onSnapshot() takes a callback that runs again every time the data changes.",
    "Call .onSnapshot(snapshot => ...).",
  ),
  query(
    "live",
    "Live Queries",
    2,
    3,
    "Get students where city equals 'Delhi'.",
    "db.collection('students').where('city', '==', 'Delhi').get();",
    ["db.collection('students').where('city', '==', 'Delhi').get();"],
    "The equality operator in a Firestore where() clause is written as '=='.",
    "Use .where('city', '==', 'Delhi').",
  ),
  query(
    "live",
    "Live Queries",
    3,
    3,
    "Get the 5 oldest students, ordered by age descending.",
    "db.collection('students').orderBy('age', 'desc').limit(5).get();",
    ["db.collection('students').orderBy('age', 'desc').limit(5).get();"],
    "Chain orderBy() and limit() before calling get().",
    "Use .orderBy('age', 'desc').limit(5).",
  ),
  query(
    "structure",
    "Ordering & Structure",
    1,
    3,
    "Add a document to the items subcollection of the order with ID '1' in the orders collection, with product 'Pen' and quantity 2.",
    "db.collection('orders').doc('1').collection('items').add({product: 'Pen', quantity: 2});",
    ["db.collection('orders').doc('1').collection('items').add({product: 'Pen', quantity: 2});"],
    "A subcollection is reached by chaining .collection() again after a specific document.",
    "Chain .doc('1').collection('items').add({...}).",
  ),
  query(
    "structure",
    "Ordering & Structure",
    2,
    3,
    "You already created a batch of writes in a variable named batch. Commit it.",
    "batch.commit();",
    ["batch.commit();"],
    "commit() sends every write queued on the batch as one atomic operation.",
    "Call .commit() on the batch variable.",
  ),
  query(
    "structure",
    "Ordering & Structure",
    3,
    3,
    "Get students ordered by name ascending.",
    "db.collection('students').orderBy('name').get();",
    ["db.collection('students').orderBy('name').get();"],
    "orderBy() sorts ascending by default when no direction is given.",
    "Use .orderBy('name') with no second argument.",
  ),
];

export const FIREBASE_COURSE: Course = {
  rounds: [
    {
      number: 1,
      title: "Round 1",
      summary: "6 basics questions and 6 query drills covering documents, CRUD, and simple queries.",
      topics: ["Basics", "CRUD", "Queries"],
      steps: ROUND_ONE_STEPS,
    },
    {
      number: 2,
      title: "Round 2",
      summary: "6 concept checks and 6 harder query drills covering live listeners, ordering, and structure.",
      topics: ["Concepts", "Live Queries", "Ordering & Structure"],
      steps: ROUND_TWO_STEPS,
    },
  ],
};
