import {type Course, makeMcqBuilder, makeQueryBuilder} from "./course-types";

const basic = makeMcqBuilder("Basics");
const concept = makeMcqBuilder("Concepts");
const query = makeQueryBuilder("code");

const ROUND_ONE_STEPS = [
  basic(
    1,
    6,
    "What is a single MongoDB record called?",
    ["Document", "Row", "Tuple", "Record ID"],
    0,
    "MongoDB stores data as documents, which are JSON-like objects.",
    "Think about the word used instead of 'row'.",
  ),
  basic(
    2,
    6,
    "What is a group of MongoDB documents called?",
    ["Collection", "Table", "Schema", "Worksheet"],
    0,
    "Documents are grouped into collections, similar to tables in SQL.",
    "It is the word used instead of 'table'.",
  ),
  basic(
    3,
    6,
    "Which field does every document get automatically as its unique identifier?",
    ["_id", "id", "uuid", "key"],
    0,
    "MongoDB assigns every document an _id field unless you provide one yourself.",
    "It starts with an underscore.",
  ),
  basic(
    4,
    6,
    "What binary format does MongoDB use to store documents on disk?",
    ["BSON", "XML", "YAML", "CSV"],
    0,
    "BSON is a binary form of JSON that adds extra types like dates and binary data.",
    "It sounds like 'JSON' with a B in front.",
  ),
  basic(
    5,
    6,
    "Which shell method inserts a single new document into a collection?",
    ["insertOne()", "insert()", "addOne()", "create()"],
    0,
    "insertOne() adds exactly one document; insertMany() adds several at once.",
    "The name describes exactly what it does: insert one.",
  ),
  basic(
    6,
    6,
    "Which shell method retrieves documents matching a filter?",
    ["find()", "get()", "select()", "fetch()"],
    0,
    "find() returns a cursor over every document that matches the filter you pass it.",
    "It is the most common read method in the Mongo shell.",
  ),
  query(
    "crud",
    "CRUD",
    1,
    3,
    "Insert one document into the students collection with name 'Asha' and age 18.",
    "db.students.insertOne({name: \"Asha\", age: 18});",
    ["db.students.insertOne({name: \"Asha\", age: 18});", "db.students.insertOne({ name: \"Asha\", age: 18 });"],
    "insertOne() takes a single object describing the new document's fields.",
    "Call db.students.insertOne({...}) with name and age.",
  ),
  query(
    "crud",
    "CRUD",
    2,
    3,
    "Update the student named 'Asha' so her age becomes 19.",
    "db.students.updateOne({name: \"Asha\"}, {$set: {age: 19}});",
    ["db.students.updateOne({name: \"Asha\"}, {$set: {age: 19}});"],
    "updateOne() takes a filter first, then an update document using operators like $set.",
    "Filter by name, then use $set to change age.",
  ),
  query(
    "crud",
    "CRUD",
    3,
    3,
    "Delete the student named 'Asha' from the students collection.",
    "db.students.deleteOne({name: \"Asha\"});",
    ["db.students.deleteOne({name: \"Asha\"});"],
    "deleteOne() removes the first document that matches the filter.",
    "Pass a filter object matching name.",
  ),
  query(
    "queries",
    "Queries",
    1,
    3,
    "Find every student in the students collection.",
    "db.students.find({});",
    ["db.students.find({});", "db.students.find();"],
    "An empty filter object matches every document in the collection.",
    "Call find() with an empty filter.",
  ),
  query(
    "queries",
    "Queries",
    2,
    3,
    "Find students older than 18.",
    "db.students.find({age: {$gt: 18}});",
    ["db.students.find({age: {$gt: 18}});"],
    "$gt means 'greater than' inside a MongoDB filter.",
    "Use {age: {$gt: 18}} as the filter.",
  ),
  query(
    "queries",
    "Queries",
    3,
    3,
    "Find every student, sorted by age from highest to lowest.",
    "db.students.find({}).sort({age: -1});",
    ["db.students.find({}).sort({age: -1});"],
    "sort() takes a field with 1 for ascending or -1 for descending.",
    "Chain .sort({age: -1}) after find({}).",
  ),
];

const ROUND_TWO_STEPS = [
  concept(
    1,
    6,
    "Which framework processes documents through a sequence of stages like $match and $group?",
    ["Aggregation pipeline", "Map only", "Stored procedure", "View chain"],
    0,
    "The aggregation pipeline passes documents through stages that each transform them.",
    "Its name describes a pipeline of stages.",
  ),
  concept(
    2,
    6,
    "Which aggregation stage joins in documents from another collection?",
    ["$lookup", "$join", "$merge", "$union"],
    0,
    "$lookup performs a left outer join against another collection.",
    "It is the stage most similar to a SQL JOIN.",
  ),
  concept(
    3,
    6,
    "Which method speeds up queries on a field by building a lookup structure?",
    ["createIndex()", "addIndex()", "makeIndex()", "buildIndex()"],
    0,
    "createIndex() builds an index MongoDB can use instead of scanning every document.",
    "The name matches the SQL idea of CREATE INDEX.",
  ),
  concept(
    4,
    6,
    "Which aggregation stage filters documents, similar to a WHERE clause?",
    ["$match", "$filter", "$where", "$find"],
    0,
    "$match narrows down documents early in the pipeline, just like WHERE in SQL.",
    "Its name means it keeps documents that match a condition.",
  ),
  concept(
    5,
    6,
    "Which aggregation stage groups documents and can compute sums or averages?",
    ["$group", "$bucket only", "$collect", "$aggregate"],
    0,
    "$group collects documents by a key and can compute totals with accumulators like $sum.",
    "It is the aggregation equivalent of GROUP BY.",
  ),
  concept(
    6,
    6,
    "Which method counts documents matching a filter?",
    ["countDocuments()", "count()", "size()", "length()"],
    0,
    "countDocuments() returns the number of documents matching a filter.",
    "The name is direct: it counts documents.",
  ),
  query(
    "aggregation",
    "Aggregation",
    1,
    3,
    "Using aggregate, match students older than 18 and group them by city, counting how many are in each city as count.",
    "db.students.aggregate([{$match: {age: {$gt: 18}}}, {$group: {_id: \"$city\", count: {$sum: 1}}}]);",
    ["db.students.aggregate([{$match: {age: {$gt: 18}}}, {$group: {_id: \"$city\", count: {$sum: 1}}}]);"],
    "$match filters first, then $group collects the remaining documents by city.",
    "Chain two stages: $match then $group, inside an array passed to aggregate().",
  ),
  query(
    "aggregation",
    "Aggregation",
    2,
    3,
    "Show only the name field, without _id, for every student.",
    "db.students.find({}, {name: 1, _id: 0});",
    ["db.students.find({}, {name: 1, _id: 0});"],
    "The second argument to find() is a projection: 1 includes a field, 0 excludes it.",
    "Pass {name: 1, _id: 0} as the projection.",
  ),
  query(
    "aggregation",
    "Aggregation",
    3,
    3,
    "Count how many students are older than 18.",
    "db.students.countDocuments({age: {$gt: 18}});",
    ["db.students.countDocuments({age: {$gt: 18}});"],
    "countDocuments() takes the same kind of filter object as find().",
    "Use the same {age: {$gt: 18}} filter with countDocuments().",
  ),
  query(
    "indexes",
    "Indexes & Joins",
    1,
    3,
    "Create an ascending index on the email field of the students collection.",
    "db.students.createIndex({email: 1});",
    ["db.students.createIndex({email: 1});"],
    "A value of 1 means ascending order for that indexed field.",
    "Call createIndex({email: 1}).",
  ),
  query(
    "indexes",
    "Indexes & Joins",
    2,
    3,
    "Using aggregate with $lookup, join each order in the orders collection to its customer in the customers collection, matching customerId to _id, and name the joined field customer.",
    "db.orders.aggregate([{$lookup: {from: \"customers\", localField: \"customerId\", foreignField: \"_id\", as: \"customer\"}}]);",
    ["db.orders.aggregate([{$lookup: {from: \"customers\", localField: \"customerId\", foreignField: \"_id\", as: \"customer\"}}]);"],
    "$lookup needs the target collection, the local and foreign fields, and a name for the result array.",
    "Fill in from, localField, foreignField, and as inside $lookup.",
  ),
  query(
    "indexes",
    "Indexes & Joins",
    3,
    3,
    "Find the first 5 students.",
    "db.students.find({}).limit(5);",
    ["db.students.find({}).limit(5);"],
    "limit() caps how many documents the cursor returns.",
    "Chain .limit(5) after find({}).",
  ),
];

export const MONGODB_COURSE: Course = {
  rounds: [
    {
      number: 1,
      title: "Round 1",
      summary: "6 basics questions and 6 query drills covering documents, CRUD, and simple queries.",
      topics: ["Basics", "CRUD", "Queries"],
      steps: ROUND_ONE_STEPS,
    },
    {
      number: 2,
      title: "Round 2",
      summary: "6 concept checks and 6 harder query drills covering aggregation, indexes, and $lookup joins.",
      topics: ["Concepts", "Aggregation", "Indexes & Joins"],
      steps: ROUND_TWO_STEPS,
    },
  ],
};
