export type MysqlTopicKey = "ddl" | "dml" | "dcl" | "tcl" | "dql";

export type MysqlBasicStep = {
  kind: "mcq";
  section: "basics";
  stepNumber: number;
  stepTotal: number;
  prompt: string;
  options: string[];
  correctIndex: number;
  explanation: string;
  hint: string;
};

export type MysqlQueryStep = {
  kind: "query";
  section: "practice";
  topicKey: MysqlTopicKey;
  topicTitle: string;
  stepNumber: number;
  stepTotal: number;
  prompt: string;
  starter: string;
  acceptedAnswers: string[];
  explanation: string;
  hint: string;
};

export type MysqlStep = MysqlBasicStep | MysqlQueryStep;

export type MysqlCourse = {
  steps: MysqlStep[];
};

const basic = (
  stepNumber: number,
  prompt: string,
  options: string[],
  correctIndex: number,
  explanation: string,
  hint: string,
): MysqlBasicStep => ({
  kind: "mcq",
  section: "basics",
  stepNumber,
  stepTotal: 10,
  prompt,
  options,
  correctIndex,
  explanation,
  hint,
});

const query = (
  topicKey: MysqlTopicKey,
  topicTitle: string,
  stepNumber: number,
  prompt: string,
  starter: string,
  acceptedAnswers: string[],
  explanation: string,
  hint: string,
): MysqlQueryStep => ({
  kind: "query",
  section: "practice",
  topicKey,
  topicTitle,
  stepNumber,
  stepTotal: 10,
  prompt,
  starter,
  acceptedAnswers,
  explanation,
  hint,
});

export const MYSQL_COURSE: MysqlCourse = {
  steps: [
    basic(
      1,
      "MySQL is best described as which type of database?",
      ["Relational database", "Image editor", "File compressor", "Message queue"],
      0,
      "MySQL is a relational database that stores structured data in tables.",
      "Think about rows, columns, and relationships.",
    ),
    basic(
      2,
      "Which statement reads data from a table?",
      ["SELECT", "INSERT", "UPDATE", "DELETE"],
      0,
      "SELECT is the SQL statement used to read rows from a table.",
      "This is the command students use first when retrieving data.",
    ),
    basic(
      3,
      "Which clause filters rows in a query?",
      ["WHERE", "GROUP BY", "ORDER BY", "LIMIT"],
      0,
      "WHERE narrows the rows before grouping or sorting happens.",
      "It is the part that removes rows that do not match a condition.",
    ),
    basic(
      4,
      "Which keyword removes duplicate rows from a result?",
      ["DISTINCT", "COUNT", "HAVING", "UNION ALL"],
      0,
      "DISTINCT removes repeated values from the result set.",
      "Look for the option that means 'only unique values'.",
    ),
    basic(
      5,
      "Which clause sorts rows?",
      ["ORDER BY", "GROUP BY", "HAVING", "JOIN"],
      0,
      "ORDER BY sorts the result set in ascending or descending order.",
      "This is the clause students use for ranking or sorting results.",
    ),
    basic(
      6,
      "Which command adds new rows to a table?",
      ["INSERT", "ALTER", "DROP", "TRUNCATE"],
      0,
      "INSERT adds one or more new rows into a table.",
      "This is the command for creating data, not changing structure.",
    ),
    basic(
      7,
      "Which command changes an existing row?",
      ["UPDATE", "CREATE", "SHOW", "DESCRIBE"],
      0,
      "UPDATE changes existing records in a table.",
      "Think of the command that edits old values.",
    ),
    basic(
      8,
      "Which command removes rows from a table?",
      ["DELETE", "DROP", "RENAME", "ALTER"],
      0,
      "DELETE removes matching rows from a table.",
      "This is the command for taking records out of a table.",
    ),
    basic(
      9,
      "Which constraint uniquely identifies a row?",
      ["PRIMARY KEY", "FOREIGN KEY", "CHECK", "DEFAULT"],
      0,
      "PRIMARY KEY makes each row unique.",
      "It is the main identifier for a row.",
    ),
    basic(
      10,
      "Which clause groups rows together?",
      ["GROUP BY", "WHERE", "ORDER BY", "LIMIT"],
      0,
      "GROUP BY collects rows into groups for aggregation.",
      "Think about summarizing rows by a shared value.",
    ),
    query(
      "ddl",
      "DDL",
      1,
      "Create a database named school_db.",
      "CREATE DATABASE school_db;",
      ["CREATE DATABASE school_db;"],
      "CREATE DATABASE builds a new database container.",
      "Use CREATE DATABASE with the requested name.",
    ),
    query(
      "ddl",
      "DDL",
      2,
      "Create a table named students with id, name, and age. Make id the primary key and auto increment it.",
      "CREATE TABLE students (...);",
      [
        "CREATE TABLE students (id INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(100), age INT);",
      ],
      "CREATE TABLE defines the structure of the students table.",
      "Use CREATE TABLE and include PRIMARY KEY AUTO_INCREMENT on id.",
    ),
    query(
      "ddl",
      "DDL",
      3,
      "Add an email column to the students table.",
      "ALTER TABLE students ADD COLUMN email VARCHAR(100);",
      ["ALTER TABLE students ADD COLUMN email VARCHAR(100);"],
      "ALTER TABLE is used to change the structure of an existing table.",
      "Use ALTER TABLE, then ADD COLUMN.",
    ),
    query(
      "ddl",
      "DDL",
      4,
      "Rename the students table to learners.",
      "RENAME TABLE students TO learners;",
      ["RENAME TABLE students TO learners;"],
      "RENAME TABLE changes the name of a table.",
      "Use RENAME TABLE and give the new table name.",
    ),
    query(
      "ddl",
      "DDL",
      5,
      "Change the age column in students to SMALLINT.",
      "ALTER TABLE students MODIFY COLUMN age SMALLINT;",
      ["ALTER TABLE students MODIFY COLUMN age SMALLINT;"],
      "ALTER TABLE with MODIFY COLUMN changes the datatype of a column.",
      "Use MODIFY COLUMN for the datatype change.",
    ),
    query(
      "ddl",
      "DDL",
      6,
      "Remove the email column from students.",
      "ALTER TABLE students DROP COLUMN email;",
      ["ALTER TABLE students DROP COLUMN email;"],
      "ALTER TABLE with DROP COLUMN removes a column from the table.",
      "Use DROP COLUMN after ALTER TABLE.",
    ),
    query(
      "ddl",
      "DDL",
      7,
      "Create an index named idx_email on the email column of students.",
      "CREATE INDEX idx_email ON students(email);",
      ["CREATE INDEX idx_email ON students(email);"],
      "CREATE INDEX helps speed up lookups on a column.",
      "Use CREATE INDEX, then name the table and column in parentheses.",
    ),
    query(
      "ddl",
      "DDL",
      8,
      "Clear all rows from the logs table but keep the table structure.",
      "TRUNCATE TABLE logs;",
      ["TRUNCATE TABLE logs;"],
      "TRUNCATE TABLE removes all rows very quickly.",
      "Use TRUNCATE TABLE, not DELETE.",
    ),
    query(
      "ddl",
      "DDL",
      9,
      "Delete the temp_users table completely.",
      "DROP TABLE temp_users;",
      ["DROP TABLE temp_users;"],
      "DROP TABLE removes the table and its data.",
      "Use DROP TABLE for deleting the whole table.",
    ),
    query(
      "ddl",
      "DDL",
      10,
      "Create a view named adult_students that shows students with age 18 or more.",
      "CREATE VIEW adult_students AS SELECT * FROM students WHERE age >= 18;",
      ["CREATE VIEW adult_students AS SELECT * FROM students WHERE age >= 18;"],
      "CREATE VIEW stores a saved query result.",
      "Use CREATE VIEW and include the SELECT statement.",
    ),
    query(
      "dml",
      "DML",
      1,
      "Insert one student named Asha who is 18 years old into the students table.",
      "INSERT INTO students (name, age) VALUES ('Asha', 18);",
      ["INSERT INTO students (name, age) VALUES ('Asha', 18);"],
      "INSERT adds a new row to a table.",
      "Use INSERT INTO with the table name, columns, and VALUES.",
    ),
    query(
      "dml",
      "DML",
      2,
      "Insert two students at once: Asha age 18 and Ravi age 20.",
      "INSERT INTO students (name, age) VALUES ('Asha', 18), ('Ravi', 20);",
      ["INSERT INTO students (name, age) VALUES ('Asha', 18), ('Ravi', 20);"],
      "Multi-row INSERT lets you add more than one row in a single statement.",
      "List both value sets in the VALUES clause.",
    ),
    query(
      "dml",
      "DML",
      3,
      "Update the age of the student with id 1 to 20.",
      "UPDATE students SET age = 20 WHERE id = 1;",
      ["UPDATE students SET age = 20 WHERE id = 1;"],
      "UPDATE changes an existing row.",
      "Use UPDATE, SET, and a WHERE clause to target the right row.",
    ),
    query(
      "dml",
      "DML",
      4,
      "Delete the student whose id is 5.",
      "DELETE FROM students WHERE id = 5;",
      ["DELETE FROM students WHERE id = 5;"],
      "DELETE removes matching rows.",
      "Use DELETE FROM and include a WHERE condition.",
    ),
    query(
      "dml",
      "DML",
      5,
      "Insert an order row with order_id 101, customer_id 3, and amount 450.",
      "INSERT INTO orders (order_id, customer_id, amount) VALUES (101, 3, 450);",
      ["INSERT INTO orders (order_id, customer_id, amount) VALUES (101, 3, 450);"],
      "INSERT can target any table and values you want to store.",
      "Use the orders table and the three requested columns.",
    ),
    query(
      "dml",
      "DML",
      6,
      "Update the city of the student named Asha to Delhi.",
      "UPDATE students SET city = 'Delhi' WHERE name = 'Asha';",
      ["UPDATE students SET city = 'Delhi' WHERE name = 'Asha';"],
      "UPDATE can change one or more columns for matching rows.",
      "Set city to Delhi and filter by the student's name.",
    ),
    query(
      "dml",
      "DML",
      7,
      "Delete all rows from temp_students where age is less than 10.",
      "DELETE FROM temp_students WHERE age < 10;",
      ["DELETE FROM temp_students WHERE age < 10;"],
      "DELETE with a WHERE clause removes only matching rows.",
      "Use the less-than sign inside the condition.",
    ),
    query(
      "dml",
      "DML",
      8,
      "Insert a grade row with student_id 1 and score 95 into the grades table.",
      "INSERT INTO grades (student_id, score) VALUES (1, 95);",
      ["INSERT INTO grades (student_id, score) VALUES (1, 95);"],
      "INSERT works the same way across different tables.",
      "Use the grades table and the requested columns.",
    ),
    query(
      "dml",
      "DML",
      9,
      "Update order 101 so its status becomes shipped.",
      "UPDATE orders SET status = 'shipped' WHERE order_id = 101;",
      ["UPDATE orders SET status = 'shipped' WHERE order_id = 101;"],
      "UPDATE is the correct command for changing stored values.",
      "Target the order with order_id 101.",
    ),
    query(
      "dml",
      "DML",
      10,
      "Delete sessions that have not been active for 30 days.",
      "DELETE FROM sessions WHERE last_active < NOW() - INTERVAL 30 DAY;",
      ["DELETE FROM sessions WHERE last_active < NOW() - INTERVAL 30 DAY;"],
      "DELETE can use date conditions to remove old rows.",
      "Use NOW() and INTERVAL 30 DAY in the condition.",
    ),
    query(
      "dcl",
      "DCL",
      1,
      "Grant SELECT access on the school_db database to the learner user at localhost.",
      "GRANT SELECT ON school_db.* TO 'learner'@'localhost';",
      ["GRANT SELECT ON school_db.* TO 'learner'@'localhost';"],
      "GRANT gives a user permission to do something.",
      "Use GRANT SELECT and the MySQL user format.",
    ),
    query(
      "dcl",
      "DCL",
      2,
      "Revoke INSERT access on school_db from the learner user at localhost.",
      "REVOKE INSERT ON school_db.* FROM 'learner'@'localhost';",
      ["REVOKE INSERT ON school_db.* FROM 'learner'@'localhost';"],
      "REVOKE removes a previously granted permission.",
      "Use REVOKE INSERT and the same MySQL user format.",
    ),
    query(
      "dcl",
      "DCL",
      3,
      "Grant all privileges on school_db to the learner user at localhost.",
      "GRANT ALL PRIVILEGES ON school_db.* TO 'learner'@'localhost';",
      ["GRANT ALL PRIVILEGES ON school_db.* TO 'learner'@'localhost';"],
      "ALL PRIVILEGES gives full access on the target database.",
      "Use GRANT ALL PRIVILEGES and school_db.*",
    ),
    query(
      "dcl",
      "DCL",
      4,
      "Remove all privileges on school_db from the learner user at localhost.",
      "REVOKE ALL PRIVILEGES ON school_db.* FROM 'learner'@'localhost';",
      ["REVOKE ALL PRIVILEGES ON school_db.* FROM 'learner'@'localhost';"],
      "REVOKE ALL PRIVILEGES removes the user's permissions.",
      "Use REVOKE ALL PRIVILEGES on the same database scope.",
    ),
    query(
      "dcl",
      "DCL",
      5,
      "Grant UPDATE access on the students table to the learner user at localhost.",
      "GRANT UPDATE ON students TO 'learner'@'localhost';",
      ["GRANT UPDATE ON students TO 'learner'@'localhost';"],
      "DCL also controls access at the table level.",
      "Use GRANT UPDATE and point it at the students table.",
    ),
    query(
      "dcl",
      "DCL",
      6,
      "Grant SELECT and INSERT access on the students table to the learner user at localhost.",
      "GRANT SELECT, INSERT ON students TO 'learner'@'localhost';",
      ["GRANT SELECT, INSERT ON students TO 'learner'@'localhost';"],
      "You can grant more than one privilege in a single statement.",
      "List both permissions after GRANT.",
    ),
    query(
      "dcl",
      "DCL",
      7,
      "Revoke SELECT access on the students table from the learner user at localhost.",
      "REVOKE SELECT ON students FROM 'learner'@'localhost';",
      ["REVOKE SELECT ON students FROM 'learner'@'localhost';"],
      "REVOKE SELECT removes only the read permission.",
      "Use REVOKE SELECT on the students table.",
    ),
    query(
      "dcl",
      "DCL",
      8,
      "Grant EXECUTE access on school_db to the learner user at localhost.",
      "GRANT EXECUTE ON school_db.* TO 'learner'@'localhost';",
      ["GRANT EXECUTE ON school_db.* TO 'learner'@'localhost';"],
      "EXECUTE is another privilege that can be granted in MySQL.",
      "Use GRANT EXECUTE with the database scope.",
    ),
    query(
      "dcl",
      "DCL",
      9,
      "Revoke DELETE access on the students table from the learner user at localhost.",
      "REVOKE DELETE ON students FROM 'learner'@'localhost';",
      ["REVOKE DELETE ON students FROM 'learner'@'localhost';"],
      "DELETE permissions can also be removed with REVOKE.",
      "Use REVOKE DELETE and the MySQL user format.",
    ),
    query(
      "dcl",
      "DCL",
      10,
      "Grant USAGE on school_db to the learner user at localhost.",
      "GRANT USAGE ON school_db.* TO 'learner'@'localhost';",
      ["GRANT USAGE ON school_db.* TO 'learner'@'localhost';"],
      "USAGE is a minimal privilege often used when setting up a user.",
      "Use GRANT USAGE and the database scope.",
    ),
    query(
      "tcl",
      "TCL",
      1,
      "Start a transaction.",
      "START TRANSACTION;",
      ["START TRANSACTION;", "BEGIN;"],
      "START TRANSACTION begins a transactional block.",
      "Use START TRANSACTION or BEGIN.",
    ),
    query(
      "tcl",
      "TCL",
      2,
      "Commit the current transaction.",
      "COMMIT;",
      ["COMMIT;"],
      "COMMIT saves the transaction changes permanently.",
      "Use COMMIT to finish and save the transaction.",
    ),
    query(
      "tcl",
      "TCL",
      3,
      "Undo the current transaction.",
      "ROLLBACK;",
      ["ROLLBACK;"],
      "ROLLBACK cancels uncommitted changes.",
      "Use ROLLBACK to reverse the transaction.",
    ),
    query(
      "tcl",
      "TCL",
      4,
      "Create a savepoint named before_update.",
      "SAVEPOINT before_update;",
      ["SAVEPOINT before_update;"],
      "SAVEPOINT creates a checkpoint inside a transaction.",
      "Use SAVEPOINT and the requested name.",
    ),
    query(
      "tcl",
      "TCL",
      5,
      "Roll back to the savepoint named before_update.",
      "ROLLBACK TO SAVEPOINT before_update;",
      ["ROLLBACK TO SAVEPOINT before_update;"],
      "ROLLBACK TO SAVEPOINT moves the transaction back to a checkpoint.",
      "Include both ROLLBACK TO and SAVEPOINT.",
    ),
    query(
      "tcl",
      "TCL",
      6,
      "Create a savepoint named after_insert.",
      "SAVEPOINT after_insert;",
      ["SAVEPOINT after_insert;"],
      "Savepoints let learners undo part of a transaction.",
      "Use the savepoint name after_insert.",
    ),
    query(
      "tcl",
      "TCL",
      7,
      "Turn off autocommit.",
      "SET autocommit = 0;",
      ["SET autocommit = 0;"],
      "Setting autocommit to 0 makes changes wait for COMMIT.",
      "Use SET autocommit = 0.",
    ),
    query(
      "tcl",
      "TCL",
      8,
      "Begin a transaction using the shorter form.",
      "BEGIN;",
      ["BEGIN;"],
      "BEGIN is a shorter way to start a transaction in MySQL.",
      "Use the one-word transaction starter.",
    ),
    query(
      "tcl",
      "TCL",
      9,
      "Release the savepoint named before_update.",
      "RELEASE SAVEPOINT before_update;",
      ["RELEASE SAVEPOINT before_update;"],
      "RELEASE SAVEPOINT removes a savepoint that is no longer needed.",
      "Use RELEASE SAVEPOINT and the savepoint name.",
    ),
    query(
      "tcl",
      "TCL",
      10,
      "Turn autocommit back on.",
      "SET autocommit = 1;",
      ["SET autocommit = 1;"],
      "Setting autocommit to 1 makes each statement commit automatically.",
      "Use SET autocommit = 1.",
    ),
    query(
      "dql",
      "DQL",
      1,
      "Select all rows from the students table.",
      "SELECT * FROM students;",
      ["SELECT * FROM students;"],
      "SELECT * reads every column from every row in the table.",
      "Use SELECT * FROM and the table name.",
    ),
    query(
      "dql",
      "DQL",
      2,
      "Select only the name and age columns from students.",
      "SELECT name, age FROM students;",
      ["SELECT name, age FROM students;"],
      "SELECT can pick only the columns you need.",
      "List the two requested columns in the SELECT clause.",
    ),
    query(
      "dql",
      "DQL",
      3,
      "Show each unique city from the students table.",
      "SELECT DISTINCT city FROM students;",
      ["SELECT DISTINCT city FROM students;"],
      "DISTINCT removes duplicate values from the result set.",
      "Use DISTINCT before the column name.",
    ),
    query(
      "dql",
      "DQL",
      4,
      "Show students older than 18.",
      "SELECT * FROM students WHERE age > 18;",
      ["SELECT * FROM students WHERE age > 18;"],
      "WHERE filters the rows before they are returned.",
      "Use WHERE with the greater-than condition.",
    ),
    query(
      "dql",
      "DQL",
      5,
      "Show all students ordered by age from highest to lowest.",
      "SELECT * FROM students ORDER BY age DESC;",
      ["SELECT * FROM students ORDER BY age DESC;"],
      "ORDER BY ... DESC sorts values from high to low.",
      "Use ORDER BY age DESC.",
    ),
    query(
      "dql",
      "DQL",
      6,
      "Show only the first 5 rows from students.",
      "SELECT * FROM students LIMIT 5;",
      ["SELECT * FROM students LIMIT 5;"],
      "LIMIT restricts how many rows are returned.",
      "Use LIMIT 5 at the end of the query.",
    ),
    query(
      "dql",
      "DQL",
      7,
      "Show each city with the number of students in it.",
      "SELECT city, COUNT(*) FROM students GROUP BY city;",
      ["SELECT city, COUNT(*) FROM students GROUP BY city;"],
      "GROUP BY collects rows into summary groups.",
      "Use COUNT(*) together with GROUP BY city.",
    ),
    query(
      "dql",
      "DQL",
      8,
      "Show cities that have more than 5 students.",
      "SELECT city, COUNT(*) FROM students GROUP BY city HAVING COUNT(*) > 5;",
      ["SELECT city, COUNT(*) FROM students GROUP BY city HAVING COUNT(*) > 5;"],
      "HAVING filters grouped results after GROUP BY runs.",
      "Use HAVING with COUNT(*) > 5.",
    ),
    query(
      "dql",
      "DQL",
      9,
      "Show students whose name starts with A.",
      "SELECT * FROM students WHERE name LIKE 'A%';",
      ["SELECT * FROM students WHERE name LIKE 'A%';"],
      "LIKE with a percent sign matches patterns in text.",
      "Use LIKE 'A%'.",
    ),
    query(
      "dql",
      "DQL",
      10,
      "Show the total number of students.",
      "SELECT COUNT(*) FROM students;",
      ["SELECT COUNT(*) FROM students;"],
      "COUNT(*) returns the number of rows.",
      "Use COUNT(*) in the SELECT clause.",
    ),
  ],
};
