import {
  type Course,
  type CourseBasicStep,
  type CourseQueryStep,
  type CourseRound,
  type CourseStep,
  makeMcqBuilder,
  makeQueryBuilder,
} from "./course-types";

export type MysqlTopicKey =
  | "ddl"
  | "dml"
  | "dcl"
  | "tcl"
  | "dql"
  | "joins"
  | "subqueries"
  | "functions"
  | "advanced";

export type MysqlBasicStep = CourseBasicStep;
export type MysqlQueryStep = CourseQueryStep;
export type MysqlStep = CourseStep;
export type MysqlRound = CourseRound;
export type MysqlCourse = Course;

// Every round in this course has 10 basics and 10 questions per topic, so these
// wrappers pin stepTotal to 10 and keep the call sites below unchanged.
const mcq = (sectionTitle: string) => {
  const build = makeMcqBuilder(sectionTitle);
  return (
    stepNumber: number,
    prompt: string,
    options: string[],
    correctIndex: number,
    explanation: string,
    hint: string,
  ): MysqlBasicStep => build(stepNumber, 10, prompt, options, correctIndex, explanation, hint);
};

const basic = mcq("Basics");
const concept = mcq("Concepts");

const buildQuery = makeQueryBuilder("sql");
const query = (
  topicKey: MysqlTopicKey,
  topicTitle: string,
  stepNumber: number,
  prompt: string,
  starter: string,
  acceptedAnswers: string[],
  explanation: string,
  hint: string,
): MysqlQueryStep =>
  buildQuery(topicKey, topicTitle, stepNumber, 10, prompt, starter, acceptedAnswers, explanation, hint);

const ROUND_ONE_STEPS: MysqlStep[] = [
  basic(
    1,
    "MySQL is best described as which type of database?",
    ["Relational database", "Image editor", "File compressor", "Message queue"],
    0,
    "MySQL is a relational database that stores structured data in tables.",
    "Think about rows, columns, and relationships.",
  ),
  basic(
    2,
    "Which statement reads data from a table?",
    ["SELECT", "INSERT", "UPDATE", "DELETE"],
    0,
    "SELECT is the SQL statement used to read rows from a table.",
    "This is the command students use first when retrieving data.",
  ),
  basic(
    3,
    "Which clause filters rows in a query?",
    ["WHERE", "GROUP BY", "ORDER BY", "LIMIT"],
    0,
    "WHERE narrows the rows before grouping or sorting happens.",
    "It is the part that removes rows that do not match a condition.",
  ),
  basic(
    4,
    "Which keyword removes duplicate rows from a result?",
    ["DISTINCT", "COUNT", "HAVING", "UNION ALL"],
    0,
    "DISTINCT removes repeated values from the result set.",
    "Look for the option that means 'only unique values'.",
  ),
  basic(
    5,
    "Which clause sorts rows?",
    ["ORDER BY", "GROUP BY", "HAVING", "JOIN"],
    0,
    "ORDER BY sorts the result set in ascending or descending order.",
    "This is the clause students use for ranking or sorting results.",
  ),
  basic(
    6,
    "Which command adds new rows to a table?",
    ["INSERT", "ALTER", "DROP", "TRUNCATE"],
    0,
    "INSERT adds one or more new rows into a table.",
    "This is the command for creating data, not changing structure.",
  ),
  basic(
    7,
    "Which command changes an existing row?",
    ["UPDATE", "CREATE", "SHOW", "DESCRIBE"],
    0,
    "UPDATE changes existing records in a table.",
    "Think of the command that edits old values.",
  ),
  basic(
    8,
    "Which command removes rows from a table?",
    ["DELETE", "DROP", "RENAME", "ALTER"],
    0,
    "DELETE removes matching rows from a table.",
    "This is the command for taking records out of a table.",
  ),
  basic(
    9,
    "Which constraint uniquely identifies a row?",
    ["PRIMARY KEY", "FOREIGN KEY", "CHECK", "DEFAULT"],
    0,
    "PRIMARY KEY makes each row unique.",
    "It is the main identifier for a row.",
  ),
  basic(
    10,
    "Which clause groups rows together?",
    ["GROUP BY", "WHERE", "ORDER BY", "LIMIT"],
    0,
    "GROUP BY collects rows into groups for aggregation.",
    "Think about summarizing rows by a shared value.",
  ),
  query(
    "ddl",
    "DDL",
    1,
    "Create a database named school_db.",
    "CREATE DATABASE school_db;",
    ["CREATE DATABASE school_db;"],
    "CREATE DATABASE builds a new database container.",
    "Use CREATE DATABASE with the requested name.",
  ),
  query(
    "ddl",
    "DDL",
    2,
    "Create a table named students with id, name, and age. Make id the primary key and auto increment it.",
    "CREATE TABLE students (...);",
    [
      "CREATE TABLE students (id INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(100), age INT);",
    ],
    "CREATE TABLE defines the structure of the students table.",
    "Use CREATE TABLE and include PRIMARY KEY AUTO_INCREMENT on id.",
  ),
  query(
    "ddl",
    "DDL",
    3,
    "Add an email column to the students table.",
    "ALTER TABLE students ADD COLUMN email VARCHAR(100);",
    ["ALTER TABLE students ADD COLUMN email VARCHAR(100);"],
    "ALTER TABLE is used to change the structure of an existing table.",
    "Use ALTER TABLE, then ADD COLUMN.",
  ),
  query(
    "ddl",
    "DDL",
    4,
    "Rename the students table to learners.",
    "RENAME TABLE students TO learners;",
    ["RENAME TABLE students TO learners;"],
    "RENAME TABLE changes the name of a table.",
    "Use RENAME TABLE and give the new table name.",
  ),
  query(
    "ddl",
    "DDL",
    5,
    "Change the age column in students to SMALLINT.",
    "ALTER TABLE students MODIFY COLUMN age SMALLINT;",
    ["ALTER TABLE students MODIFY COLUMN age SMALLINT;"],
    "ALTER TABLE with MODIFY COLUMN changes the datatype of a column.",
    "Use MODIFY COLUMN for the datatype change.",
  ),
  query(
    "ddl",
    "DDL",
    6,
    "Remove the email column from students.",
    "ALTER TABLE students DROP COLUMN email;",
    ["ALTER TABLE students DROP COLUMN email;"],
    "ALTER TABLE with DROP COLUMN removes a column from the table.",
    "Use DROP COLUMN after ALTER TABLE.",
  ),
  query(
    "ddl",
    "DDL",
    7,
    "Create an index named idx_email on the email column of students.",
    "CREATE INDEX idx_email ON students(email);",
    ["CREATE INDEX idx_email ON students(email);"],
    "CREATE INDEX helps speed up lookups on a column.",
    "Use CREATE INDEX, then name the table and column in parentheses.",
  ),
  query(
    "ddl",
    "DDL",
    8,
    "Clear all rows from the logs table but keep the table structure.",
    "TRUNCATE TABLE logs;",
    ["TRUNCATE TABLE logs;"],
    "TRUNCATE TABLE removes all rows very quickly.",
    "Use TRUNCATE TABLE, not DELETE.",
  ),
  query(
    "ddl",
    "DDL",
    9,
    "Delete the temp_users table completely.",
    "DROP TABLE temp_users;",
    ["DROP TABLE temp_users;"],
    "DROP TABLE removes the table and its data.",
    "Use DROP TABLE for deleting the whole table.",
  ),
  query(
    "ddl",
    "DDL",
    10,
    "Create a view named adult_students that shows students with age 18 or more.",
    "CREATE VIEW adult_students AS SELECT * FROM students WHERE age >= 18;",
    ["CREATE VIEW adult_students AS SELECT * FROM students WHERE age >= 18;"],
    "CREATE VIEW stores a saved query result.",
    "Use CREATE VIEW and include the SELECT statement.",
  ),
  query(
    "dml",
    "DML",
    1,
    "Insert one student named Asha who is 18 years old into the students table.",
    "INSERT INTO students (name, age) VALUES ('Asha', 18);",
    ["INSERT INTO students (name, age) VALUES ('Asha', 18);"],
    "INSERT adds a new row to a table.",
    "Use INSERT INTO with the table name, columns, and VALUES.",
  ),
  query(
    "dml",
    "DML",
    2,
    "Insert two students at once: Asha age 18 and Ravi age 20.",
    "INSERT INTO students (name, age) VALUES ('Asha', 18), ('Ravi', 20);",
    ["INSERT INTO students (name, age) VALUES ('Asha', 18), ('Ravi', 20);"],
    "Multi-row INSERT lets you add more than one row in a single statement.",
    "List both value sets in the VALUES clause.",
  ),
  query(
    "dml",
    "DML",
    3,
    "Update the age of the student with id 1 to 20.",
    "UPDATE students SET age = 20 WHERE id = 1;",
    ["UPDATE students SET age = 20 WHERE id = 1;"],
    "UPDATE changes an existing row.",
    "Use UPDATE, SET, and a WHERE clause to target the right row.",
  ),
  query(
    "dml",
    "DML",
    4,
    "Delete the student whose id is 5.",
    "DELETE FROM students WHERE id = 5;",
    ["DELETE FROM students WHERE id = 5;"],
    "DELETE removes matching rows.",
    "Use DELETE FROM and include a WHERE condition.",
  ),
  query(
    "dml",
    "DML",
    5,
    "Insert an order row with order_id 101, customer_id 3, and amount 450.",
    "INSERT INTO orders (order_id, customer_id, amount) VALUES (101, 3, 450);",
    ["INSERT INTO orders (order_id, customer_id, amount) VALUES (101, 3, 450);"],
    "INSERT can target any table and values you want to store.",
    "Use the orders table and the three requested columns.",
  ),
  query(
    "dml",
    "DML",
    6,
    "Update the city of the student named Asha to Delhi.",
    "UPDATE students SET city = 'Delhi' WHERE name = 'Asha';",
    ["UPDATE students SET city = 'Delhi' WHERE name = 'Asha';"],
    "UPDATE can change one or more columns for matching rows.",
    "Set city to Delhi and filter by the student's name.",
  ),
  query(
    "dml",
    "DML",
    7,
    "Delete all rows from temp_students where age is less than 10.",
    "DELETE FROM temp_students WHERE age < 10;",
    ["DELETE FROM temp_students WHERE age < 10;"],
    "DELETE with a WHERE clause removes only matching rows.",
    "Use the less-than sign inside the condition.",
  ),
  query(
    "dml",
    "DML",
    8,
    "Insert a grade row with student_id 1 and score 95 into the grades table.",
    "INSERT INTO grades (student_id, score) VALUES (1, 95);",
    ["INSERT INTO grades (student_id, score) VALUES (1, 95);"],
    "INSERT works the same way across different tables.",
    "Use the grades table and the requested columns.",
  ),
  query(
    "dml",
    "DML",
    9,
    "Update order 101 so its status becomes shipped.",
    "UPDATE orders SET status = 'shipped' WHERE order_id = 101;",
    ["UPDATE orders SET status = 'shipped' WHERE order_id = 101;"],
    "UPDATE is the correct command for changing stored values.",
    "Target the order with order_id 101.",
  ),
  query(
    "dml",
    "DML",
    10,
    "Delete sessions that have not been active for 30 days.",
    "DELETE FROM sessions WHERE last_active < NOW() - INTERVAL 30 DAY;",
    ["DELETE FROM sessions WHERE last_active < NOW() - INTERVAL 30 DAY;"],
    "DELETE can use date conditions to remove old rows.",
    "Use NOW() and INTERVAL 30 DAY in the condition.",
  ),
  query(
    "dcl",
    "DCL",
    1,
    "Grant SELECT access on the school_db database to the learner user at localhost.",
    "GRANT SELECT ON school_db.* TO 'learner'@'localhost';",
    ["GRANT SELECT ON school_db.* TO 'learner'@'localhost';"],
    "GRANT gives a user permission to do something.",
    "Use GRANT SELECT and the MySQL user format.",
  ),
  query(
    "dcl",
    "DCL",
    2,
    "Revoke INSERT access on school_db from the learner user at localhost.",
    "REVOKE INSERT ON school_db.* FROM 'learner'@'localhost';",
    ["REVOKE INSERT ON school_db.* FROM 'learner'@'localhost';"],
    "REVOKE removes a previously granted permission.",
    "Use REVOKE INSERT and the same MySQL user format.",
  ),
  query(
    "dcl",
    "DCL",
    3,
    "Grant all privileges on school_db to the learner user at localhost.",
    "GRANT ALL PRIVILEGES ON school_db.* TO 'learner'@'localhost';",
    ["GRANT ALL PRIVILEGES ON school_db.* TO 'learner'@'localhost';"],
    "ALL PRIVILEGES gives full access on the target database.",
    "Use GRANT ALL PRIVILEGES and school_db.*",
  ),
  query(
    "dcl",
    "DCL",
    4,
    "Remove all privileges on school_db from the learner user at localhost.",
    "REVOKE ALL PRIVILEGES ON school_db.* FROM 'learner'@'localhost';",
    ["REVOKE ALL PRIVILEGES ON school_db.* FROM 'learner'@'localhost';"],
    "REVOKE ALL PRIVILEGES removes the user's permissions.",
    "Use REVOKE ALL PRIVILEGES on the same database scope.",
  ),
  query(
    "dcl",
    "DCL",
    5,
    "Grant UPDATE access on the students table to the learner user at localhost.",
    "GRANT UPDATE ON students TO 'learner'@'localhost';",
    ["GRANT UPDATE ON students TO 'learner'@'localhost';"],
    "DCL also controls access at the table level.",
    "Use GRANT UPDATE and point it at the students table.",
  ),
  query(
    "dcl",
    "DCL",
    6,
    "Grant SELECT and INSERT access on the students table to the learner user at localhost.",
    "GRANT SELECT, INSERT ON students TO 'learner'@'localhost';",
    ["GRANT SELECT, INSERT ON students TO 'learner'@'localhost';"],
    "You can grant more than one privilege in a single statement.",
    "List both permissions after GRANT.",
  ),
  query(
    "dcl",
    "DCL",
    7,
    "Revoke SELECT access on the students table from the learner user at localhost.",
    "REVOKE SELECT ON students FROM 'learner'@'localhost';",
    ["REVOKE SELECT ON students FROM 'learner'@'localhost';"],
    "REVOKE SELECT removes only the read permission.",
    "Use REVOKE SELECT on the students table.",
  ),
  query(
    "dcl",
    "DCL",
    8,
    "Grant EXECUTE access on school_db to the learner user at localhost.",
    "GRANT EXECUTE ON school_db.* TO 'learner'@'localhost';",
    ["GRANT EXECUTE ON school_db.* TO 'learner'@'localhost';"],
    "EXECUTE is another privilege that can be granted in MySQL.",
    "Use GRANT EXECUTE with the database scope.",
  ),
  query(
    "dcl",
    "DCL",
    9,
    "Revoke DELETE access on the students table from the learner user at localhost.",
    "REVOKE DELETE ON students FROM 'learner'@'localhost';",
    ["REVOKE DELETE ON students FROM 'learner'@'localhost';"],
    "DELETE permissions can also be removed with REVOKE.",
    "Use REVOKE DELETE and the MySQL user format.",
  ),
  query(
    "dcl",
    "DCL",
    10,
    "Grant USAGE on school_db to the learner user at localhost.",
    "GRANT USAGE ON school_db.* TO 'learner'@'localhost';",
    ["GRANT USAGE ON school_db.* TO 'learner'@'localhost';"],
    "USAGE is a minimal privilege often used when setting up a user.",
    "Use GRANT USAGE and the database scope.",
  ),
  query(
    "tcl",
    "TCL",
    1,
    "Start a transaction.",
    "START TRANSACTION;",
    ["START TRANSACTION;", "BEGIN;"],
    "START TRANSACTION begins a transactional block.",
    "Use START TRANSACTION or BEGIN.",
  ),
  query(
    "tcl",
    "TCL",
    2,
    "Commit the current transaction.",
    "COMMIT;",
    ["COMMIT;"],
    "COMMIT saves the transaction changes permanently.",
    "Use COMMIT to finish and save the transaction.",
  ),
  query(
    "tcl",
    "TCL",
    3,
    "Undo the current transaction.",
    "ROLLBACK;",
    ["ROLLBACK;"],
    "ROLLBACK cancels uncommitted changes.",
    "Use ROLLBACK to reverse the transaction.",
  ),
  query(
    "tcl",
    "TCL",
    4,
    "Create a savepoint named before_update.",
    "SAVEPOINT before_update;",
    ["SAVEPOINT before_update;"],
    "SAVEPOINT creates a checkpoint inside a transaction.",
    "Use SAVEPOINT and the requested name.",
  ),
  query(
    "tcl",
    "TCL",
    5,
    "Roll back to the savepoint named before_update.",
    "ROLLBACK TO SAVEPOINT before_update;",
    ["ROLLBACK TO SAVEPOINT before_update;"],
    "ROLLBACK TO SAVEPOINT moves the transaction back to a checkpoint.",
    "Include both ROLLBACK TO and SAVEPOINT.",
  ),
  query(
    "tcl",
    "TCL",
    6,
    "Create a savepoint named after_insert.",
    "SAVEPOINT after_insert;",
    ["SAVEPOINT after_insert;"],
    "Savepoints let learners undo part of a transaction.",
    "Use the savepoint name after_insert.",
  ),
  query(
    "tcl",
    "TCL",
    7,
    "Turn off autocommit.",
    "SET autocommit = 0;",
    ["SET autocommit = 0;"],
    "Setting autocommit to 0 makes changes wait for COMMIT.",
    "Use SET autocommit = 0.",
  ),
  query(
    "tcl",
    "TCL",
    8,
    "Begin a transaction using the shorter form.",
    "BEGIN;",
    ["BEGIN;"],
    "BEGIN is a shorter way to start a transaction in MySQL.",
    "Use the one-word transaction starter.",
  ),
  query(
    "tcl",
    "TCL",
    9,
    "Release the savepoint named before_update.",
    "RELEASE SAVEPOINT before_update;",
    ["RELEASE SAVEPOINT before_update;"],
    "RELEASE SAVEPOINT removes a savepoint that is no longer needed.",
    "Use RELEASE SAVEPOINT and the savepoint name.",
  ),
  query(
    "tcl",
    "TCL",
    10,
    "Turn autocommit back on.",
    "SET autocommit = 1;",
    ["SET autocommit = 1;"],
    "Setting autocommit to 1 makes each statement commit automatically.",
    "Use SET autocommit = 1.",
  ),
  query(
    "dql",
    "DQL",
    1,
    "Select all rows from the students table.",
    "SELECT * FROM students;",
    ["SELECT * FROM students;"],
    "SELECT * reads every column from every row in the table.",
    "Use SELECT * FROM and the table name.",
  ),
  query(
    "dql",
    "DQL",
    2,
    "Select only the name and age columns from students.",
    "SELECT name, age FROM students;",
    ["SELECT name, age FROM students;"],
    "SELECT can pick only the columns you need.",
    "List the two requested columns in the SELECT clause.",
  ),
  query(
    "dql",
    "DQL",
    3,
    "Show each unique city from the students table.",
    "SELECT DISTINCT city FROM students;",
    ["SELECT DISTINCT city FROM students;"],
    "DISTINCT removes duplicate values from the result set.",
    "Use DISTINCT before the column name.",
  ),
  query(
    "dql",
    "DQL",
    4,
    "Show students older than 18.",
    "SELECT * FROM students WHERE age > 18;",
    ["SELECT * FROM students WHERE age > 18;"],
    "WHERE filters the rows before they are returned.",
    "Use WHERE with the greater-than condition.",
  ),
  query(
    "dql",
    "DQL",
    5,
    "Show all students ordered by age from highest to lowest.",
    "SELECT * FROM students ORDER BY age DESC;",
    ["SELECT * FROM students ORDER BY age DESC;"],
    "ORDER BY ... DESC sorts values from high to low.",
    "Use ORDER BY age DESC.",
  ),
  query(
    "dql",
    "DQL",
    6,
    "Show only the first 5 rows from students.",
    "SELECT * FROM students LIMIT 5;",
    ["SELECT * FROM students LIMIT 5;"],
    "LIMIT restricts how many rows are returned.",
    "Use LIMIT 5 at the end of the query.",
  ),
  query(
    "dql",
    "DQL",
    7,
    "Show each city with the number of students in it.",
    "SELECT city, COUNT(*) FROM students GROUP BY city;",
    ["SELECT city, COUNT(*) FROM students GROUP BY city;"],
    "GROUP BY collects rows into summary groups.",
    "Use COUNT(*) together with GROUP BY city.",
  ),
  query(
    "dql",
    "DQL",
    8,
    "Show cities that have more than 5 students.",
    "SELECT city, COUNT(*) FROM students GROUP BY city HAVING COUNT(*) > 5;",
    ["SELECT city, COUNT(*) FROM students GROUP BY city HAVING COUNT(*) > 5;"],
    "HAVING filters grouped results after GROUP BY runs.",
    "Use HAVING with COUNT(*) > 5.",
  ),
  query(
    "dql",
    "DQL",
    9,
    "Show students whose name starts with A.",
    "SELECT * FROM students WHERE name LIKE 'A%';",
    ["SELECT * FROM students WHERE name LIKE 'A%';"],
    "LIKE with a percent sign matches patterns in text.",
    "Use LIKE 'A%'.",
  ),
  query(
    "dql",
    "DQL",
    10,
    "Show the total number of students.",
    "SELECT COUNT(*) FROM students;",
    ["SELECT COUNT(*) FROM students;"],
    "COUNT(*) returns the number of rows.",
    "Use COUNT(*) in the SELECT clause.",
  ),
];

const ROUND_TWO_STEPS: MysqlStep[] = [
  concept(
    1,
    "Which JOIN returns only the rows that have a match in both tables?",
    ["INNER JOIN", "LEFT JOIN", "RIGHT JOIN", "CROSS JOIN"],
    0,
    "INNER JOIN keeps only rows where the join condition matches on both sides.",
    "Think about the join that drops unmatched rows from both tables.",
  ),
  concept(
    2,
    "Which JOIN keeps every row from the left table, even without a match?",
    ["LEFT JOIN", "INNER JOIN", "CROSS JOIN", "SELF JOIN"],
    0,
    "LEFT JOIN returns all left-table rows and fills missing right-side values with NULL.",
    "The name of the join points to the table that is always kept.",
  ),
  concept(
    3,
    "Which clause filters groups after aggregation?",
    ["HAVING", "WHERE", "ORDER BY", "LIMIT"],
    0,
    "HAVING runs after GROUP BY, so it can filter on aggregates like COUNT(*) or SUM().",
    "WHERE runs before grouping, so it cannot see aggregate results.",
  ),
  concept(
    4,
    "What does a FOREIGN KEY do?",
    [
      "Links a column to a key in another table",
      "Encrypts a column",
      "Sorts rows automatically",
      "Removes duplicate rows",
    ],
    0,
    "A FOREIGN KEY enforces that a value exists in the referenced table's key column.",
    "Think about relationships between tables.",
  ),
  concept(
    5,
    "Which operator checks whether a value is in a list or subquery result?",
    ["IN", "LIKE", "BETWEEN", "IS"],
    0,
    "IN tests membership, for example WHERE id IN (1, 2, 3) or WHERE id IN (SELECT ...).",
    "It reads naturally: is this value in that set?",
  ),
  concept(
    6,
    "Which keyword combines the results of two SELECTs and removes duplicates?",
    ["UNION", "UNION ALL", "JOIN", "INTERSECT ALL"],
    0,
    "UNION stacks the results of two queries and removes duplicate rows. UNION ALL keeps duplicates.",
    "One option keeps duplicates, the other removes them.",
  ),
  concept(
    7,
    "How do you correctly check whether a column has no value?",
    ["WHERE city IS NULL", "WHERE city = NULL", "WHERE city == NULL", "WHERE city EMPTY"],
    0,
    "NULL is not equal to anything, not even NULL, so you must use IS NULL or IS NOT NULL.",
    "Comparing with = never matches NULL.",
  ),
  concept(
    8,
    "Which operator matches an inclusive range of values?",
    ["BETWEEN", "IN", "LIKE", "ANY"],
    0,
    "BETWEEN a AND b includes both a and b.",
    "It is followed by a lower value, AND, and an upper value.",
  ),
  concept(
    9,
    "Which function joins strings together in MySQL?",
    ["CONCAT()", "SUM()", "MERGE()", "JOIN()"],
    0,
    "CONCAT() joins two or more strings into one value.",
    "Its name is short for concatenate.",
  ),
  concept(
    10,
    "What is a subquery?",
    [
      "A query nested inside another query",
      "A backup copy of a table",
      "A query that only reads indexes",
      "A stored user permission",
    ],
    0,
    "A subquery is a SELECT placed inside another statement, such as in WHERE, FROM, or SELECT.",
    "Think about a query inside parentheses.",
  ),
  query(
    "joins",
    "JOINs",
    1,
    "Show each order's order_id with the customer's name. Join orders and customers where orders.customer_id matches customers.id.",
    "SELECT orders.order_id, customers.name FROM orders JOIN customers ON orders.customer_id = customers.id;",
    [
      "SELECT orders.order_id, customers.name FROM orders JOIN customers ON orders.customer_id = customers.id;",
      "SELECT o.order_id, c.name FROM orders o JOIN customers c ON o.customer_id = c.id;",
    ],
    "An INNER JOIN combines rows from two tables where the join condition matches.",
    "Use JOIN ... ON and qualify the columns with their table names.",
  ),
  query(
    "joins",
    "JOINs",
    2,
    "Show every customer's name and their order amount, including customers with no orders. Start FROM customers.",
    "SELECT customers.name, orders.amount FROM customers LEFT JOIN orders ON customers.id = orders.customer_id;",
    [
      "SELECT customers.name, orders.amount FROM customers LEFT JOIN orders ON customers.id = orders.customer_id;",
      "SELECT c.name, o.amount FROM customers c LEFT JOIN orders o ON c.id = o.customer_id;",
    ],
    "LEFT JOIN keeps every customer, even when there is no matching order.",
    "Use LEFT JOIN so the customers table is always kept.",
  ),
  query(
    "joins",
    "JOINs",
    3,
    "Using a RIGHT JOIN from customers to orders, show every order's order_id with the customer's name.",
    "SELECT orders.order_id, customers.name FROM customers RIGHT JOIN orders ON customers.id = orders.customer_id;",
    [
      "SELECT orders.order_id, customers.name FROM customers RIGHT JOIN orders ON customers.id = orders.customer_id;",
      "SELECT o.order_id, c.name FROM customers c RIGHT JOIN orders o ON c.id = o.customer_id;",
    ],
    "RIGHT JOIN keeps every row from the right table, here orders.",
    "Write FROM customers RIGHT JOIN orders.",
  ),
  query(
    "joins",
    "JOINs",
    4,
    "Show each student's name with the title of every course they are enrolled in. Join students to enrollments on student_id, then enrollments to courses on course_id.",
    "SELECT students.name, courses.title FROM students JOIN enrollments ON students.id = enrollments.student_id JOIN courses ON enrollments.course_id = courses.id;",
    [
      "SELECT students.name, courses.title FROM students JOIN enrollments ON students.id = enrollments.student_id JOIN courses ON enrollments.course_id = courses.id;",
      "SELECT s.name, c.title FROM students s JOIN enrollments e ON s.id = e.student_id JOIN courses c ON e.course_id = c.id;",
    ],
    "You can chain JOINs to walk through a linking table like enrollments.",
    "Use two JOIN ... ON clauses, one for each hop.",
  ),
  query(
    "joins",
    "JOINs",
    5,
    "Show each employee's name with their manager's name. Self join employees with alias e for the employee and m for the manager, where e.manager_id matches m.id.",
    "SELECT e.name, m.name FROM employees e JOIN employees m ON e.manager_id = m.id;",
    ["SELECT e.name, m.name FROM employees e JOIN employees m ON e.manager_id = m.id;"],
    "A self join joins a table to itself, using aliases to tell the two copies apart.",
    "Use the employees table twice with aliases e and m.",
  ),
  query(
    "joins",
    "JOINs",
    6,
    "List every combination of rows from the sizes and colors tables.",
    "SELECT * FROM sizes CROSS JOIN colors;",
    ["SELECT * FROM sizes CROSS JOIN colors;"],
    "CROSS JOIN returns every row of one table paired with every row of the other.",
    "Use CROSS JOIN, which needs no ON condition.",
  ),
  query(
    "joins",
    "JOINs",
    7,
    "Show the names of customers who placed an order with an amount greater than 500.",
    "SELECT customers.name FROM customers JOIN orders ON customers.id = orders.customer_id WHERE orders.amount > 500;",
    [
      "SELECT customers.name FROM customers JOIN orders ON customers.id = orders.customer_id WHERE orders.amount > 500;",
      "SELECT c.name FROM customers c JOIN orders o ON c.id = o.customer_id WHERE o.amount > 500;",
    ],
    "You can filter joined rows with WHERE just like a single-table query.",
    "JOIN first, then add WHERE orders.amount > 500.",
  ),
  query(
    "joins",
    "JOINs",
    8,
    "Show the names of customers who have never placed an order, using a LEFT JOIN and checking orders.order_id for NULL.",
    "SELECT customers.name FROM customers LEFT JOIN orders ON customers.id = orders.customer_id WHERE orders.order_id IS NULL;",
    [
      "SELECT customers.name FROM customers LEFT JOIN orders ON customers.id = orders.customer_id WHERE orders.order_id IS NULL;",
      "SELECT c.name FROM customers c LEFT JOIN orders o ON c.id = o.customer_id WHERE o.order_id IS NULL;",
    ],
    "A LEFT JOIN plus IS NULL finds rows that have no match on the right side.",
    "Unmatched customers have NULL in every orders column.",
  ),
  query(
    "joins",
    "JOINs",
    9,
    "Show each customer's name with the total amount of all their orders.",
    "SELECT customers.name, SUM(orders.amount) FROM customers JOIN orders ON customers.id = orders.customer_id GROUP BY customers.name;",
    [
      "SELECT customers.name, SUM(orders.amount) FROM customers JOIN orders ON customers.id = orders.customer_id GROUP BY customers.name;",
      "SELECT c.name, SUM(o.amount) FROM customers c JOIN orders o ON c.id = o.customer_id GROUP BY c.name;",
    ],
    "Joining and then grouping lets you summarize related rows per customer.",
    "Use SUM(orders.amount) and GROUP BY customers.name.",
  ),
  query(
    "joins",
    "JOINs",
    10,
    "Show each employee's name with their department's name. Join employees and departments where employees.department_id matches departments.id.",
    "SELECT employees.name, departments.name FROM employees JOIN departments ON employees.department_id = departments.id;",
    [
      "SELECT employees.name, departments.name FROM employees JOIN departments ON employees.department_id = departments.id;",
      "SELECT e.name, d.name FROM employees e JOIN departments d ON e.department_id = d.id;",
    ],
    "Joining on a foreign key is the most common JOIN you will write.",
    "Both tables have a name column, so prefix each with its table.",
  ),
  query(
    "subqueries",
    "Subqueries",
    1,
    "Show all students whose age is greater than the average age of all students.",
    "SELECT * FROM students WHERE age > (SELECT AVG(age) FROM students);",
    ["SELECT * FROM students WHERE age > (SELECT AVG(age) FROM students);"],
    "A scalar subquery returns a single value you can compare against.",
    "Put SELECT AVG(age) FROM students inside parentheses.",
  ),
  query(
    "subqueries",
    "Subqueries",
    2,
    "Show the names of customers who have placed at least one order, using IN with a subquery on orders.",
    "SELECT name FROM customers WHERE id IN (SELECT customer_id FROM orders);",
    ["SELECT name FROM customers WHERE id IN (SELECT customer_id FROM orders);"],
    "IN with a subquery checks whether a value appears in another query's results.",
    "Compare customers.id with the customer_id values from orders.",
  ),
  query(
    "subqueries",
    "Subqueries",
    3,
    "Show the names of customers who have never placed an order, using NOT IN with a subquery.",
    "SELECT name FROM customers WHERE id NOT IN (SELECT customer_id FROM orders);",
    ["SELECT name FROM customers WHERE id NOT IN (SELECT customer_id FROM orders);"],
    "NOT IN keeps only the values that do not appear in the subquery.",
    "It is the same shape as IN, with NOT in front.",
  ),
  query(
    "subqueries",
    "Subqueries",
    4,
    "Show the names of customers who have at least one order, using EXISTS with a correlated subquery that selects 1.",
    "SELECT name FROM customers WHERE EXISTS (SELECT 1 FROM orders WHERE orders.customer_id = customers.id);",
    [
      "SELECT name FROM customers WHERE EXISTS (SELECT 1 FROM orders WHERE orders.customer_id = customers.id);",
      "SELECT name FROM customers WHERE EXISTS (SELECT * FROM orders WHERE orders.customer_id = customers.id);",
    ],
    "EXISTS returns true as soon as the subquery finds one matching row.",
    "The inner WHERE links orders back to the outer customers row.",
  ),
  query(
    "subqueries",
    "Subqueries",
    5,
    "Show the employee or employees with the highest salary.",
    "SELECT * FROM employees WHERE salary = (SELECT MAX(salary) FROM employees);",
    ["SELECT * FROM employees WHERE salary = (SELECT MAX(salary) FROM employees);"],
    "Comparing against MAX() in a subquery returns every row that ties for the top value.",
    "Use a subquery with MAX(salary).",
  ),
  query(
    "subqueries",
    "Subqueries",
    6,
    "Show the second highest salary from employees.",
    "SELECT MAX(salary) FROM employees WHERE salary < (SELECT MAX(salary) FROM employees);",
    ["SELECT MAX(salary) FROM employees WHERE salary < (SELECT MAX(salary) FROM employees);"],
    "The highest salary below the overall maximum is the second highest.",
    "Take MAX(salary) again, but only for salaries below the top one.",
  ),
  query(
    "subqueries",
    "Subqueries",
    7,
    "Using a derived table named t with a total column, show the average of each customer's total order amount.",
    "SELECT AVG(total) FROM (SELECT customer_id, SUM(amount) AS total FROM orders GROUP BY customer_id) AS t;",
    ["SELECT AVG(total) FROM (SELECT customer_id, SUM(amount) AS total FROM orders GROUP BY customer_id) AS t;"],
    "A subquery in FROM acts like a temporary table, and MySQL requires it to have an alias.",
    "Group orders by customer_id inside the parentheses, then average the totals outside.",
  ),
  query(
    "subqueries",
    "Subqueries",
    8,
    "Show employees who earn more than the average salary of their own department. Alias the outer table as e.",
    "SELECT * FROM employees e WHERE salary > (SELECT AVG(salary) FROM employees WHERE department_id = e.department_id);",
    [
      "SELECT * FROM employees e WHERE salary > (SELECT AVG(salary) FROM employees WHERE department_id = e.department_id);",
      "SELECT * FROM employees e WHERE e.salary > (SELECT AVG(salary) FROM employees WHERE department_id = e.department_id);",
    ],
    "A correlated subquery runs once per outer row and can reference the outer row's columns.",
    "Inside the subquery, compare department_id with e.department_id.",
  ),
  query(
    "subqueries",
    "Subqueries",
    9,
    "Using a CTE named high_orders that holds all orders with amount over 1000, select everything from high_orders.",
    "WITH high_orders AS (SELECT * FROM orders WHERE amount > 1000) SELECT * FROM high_orders;",
    ["WITH high_orders AS (SELECT * FROM orders WHERE amount > 1000) SELECT * FROM high_orders;"],
    "A CTE (WITH ... AS) names a subquery so the main query reads more clearly.",
    "Start with WITH high_orders AS ( ... ).",
  ),
  query(
    "subqueries",
    "Subqueries",
    10,
    "Show orders whose amount is greater than all orders placed by customer 3, using ALL.",
    "SELECT * FROM orders WHERE amount > ALL (SELECT amount FROM orders WHERE customer_id = 3);",
    ["SELECT * FROM orders WHERE amount > ALL (SELECT amount FROM orders WHERE customer_id = 3);"],
    "> ALL means greater than every value returned by the subquery.",
    "Place ALL between the comparison and the subquery.",
  ),
  query(
    "functions",
    "Functions",
    1,
    "Show the average salary of all employees.",
    "SELECT AVG(salary) FROM employees;",
    ["SELECT AVG(salary) FROM employees;"],
    "AVG() returns the mean of a numeric column.",
    "Use AVG(salary).",
  ),
  query(
    "functions",
    "Functions",
    2,
    "Show the highest and the lowest order amount, in that order.",
    "SELECT MAX(amount), MIN(amount) FROM orders;",
    ["SELECT MAX(amount), MIN(amount) FROM orders;"],
    "MAX() and MIN() find the largest and smallest values in a column.",
    "Put both aggregates in the SELECT list.",
  ),
  query(
    "functions",
    "Functions",
    3,
    "Show the total amount of all orders.",
    "SELECT SUM(amount) FROM orders;",
    ["SELECT SUM(amount) FROM orders;"],
    "SUM() adds up every value in a column.",
    "Use SUM(amount).",
  ),
  query(
    "functions",
    "Functions",
    4,
    "Show each student's name in uppercase.",
    "SELECT UPPER(name) FROM students;",
    ["SELECT UPPER(name) FROM students;", "SELECT UCASE(name) FROM students;"],
    "UPPER() converts text to capital letters.",
    "Wrap the name column in UPPER().",
  ),
  query(
    "functions",
    "Functions",
    5,
    "Show each student's name and city as a single column, separated by a comma and a space.",
    "SELECT CONCAT(name, ', ', city) FROM students;",
    ["SELECT CONCAT(name, ', ', city) FROM students;", "SELECT CONCAT_WS(', ', name, city) FROM students;"],
    "CONCAT() joins several strings into one.",
    "Pass name, the separator string, and city to CONCAT().",
  ),
  query(
    "functions",
    "Functions",
    6,
    "Show each student's name and city, showing 'Unknown' when the city is NULL.",
    "SELECT name, IFNULL(city, 'Unknown') FROM students;",
    ["SELECT name, IFNULL(city, 'Unknown') FROM students;", "SELECT name, COALESCE(city, 'Unknown') FROM students;"],
    "IFNULL() and COALESCE() replace NULL with a fallback value.",
    "Use IFNULL(city, 'Unknown').",
  ),
  query(
    "functions",
    "Functions",
    7,
    "Show today's date.",
    "SELECT CURDATE();",
    ["SELECT CURDATE();", "SELECT CURRENT_DATE();", "SELECT CURRENT_DATE;"],
    "CURDATE() returns the current date without a time part.",
    "SELECT a date function with no FROM clause.",
  ),
  query(
    "functions",
    "Functions",
    8,
    "Show each order's order_id and the year of its order_date.",
    "SELECT order_id, YEAR(order_date) FROM orders;",
    ["SELECT order_id, YEAR(order_date) FROM orders;"],
    "YEAR() extracts the year from a date value.",
    "Use YEAR(order_date).",
  ),
  query(
    "functions",
    "Functions",
    9,
    "Show each order's order_id and its amount rounded to the nearest whole number.",
    "SELECT order_id, ROUND(amount) FROM orders;",
    ["SELECT order_id, ROUND(amount) FROM orders;", "SELECT order_id, ROUND(amount, 0) FROM orders;"],
    "ROUND() rounds a number, optionally to a number of decimal places.",
    "Use ROUND(amount).",
  ),
  query(
    "functions",
    "Functions",
    10,
    "Show each department_id with its number of employees and their average salary.",
    "SELECT department_id, COUNT(*), AVG(salary) FROM employees GROUP BY department_id;",
    ["SELECT department_id, COUNT(*), AVG(salary) FROM employees GROUP BY department_id;"],
    "You can use several aggregate functions in the same grouped query.",
    "Use COUNT(*) and AVG(salary) with GROUP BY department_id.",
  ),
  query(
    "advanced",
    "Advanced",
    1,
    "Create an orders table with order_id as an auto-increment primary key, customer_id INT, and a foreign key from customer_id to customers(id).",
    "CREATE TABLE orders (order_id INT PRIMARY KEY AUTO_INCREMENT, customer_id INT, FOREIGN KEY (customer_id) REFERENCES customers(id));",
    ["CREATE TABLE orders (order_id INT PRIMARY KEY AUTO_INCREMENT, customer_id INT, FOREIGN KEY (customer_id) REFERENCES customers(id));"],
    "FOREIGN KEY ... REFERENCES links a column to another table's key.",
    "Add FOREIGN KEY (customer_id) REFERENCES customers(id) after the columns.",
  ),
  query(
    "advanced",
    "Advanced",
    2,
    "Add a UNIQUE constraint on the email column of students.",
    "ALTER TABLE students ADD UNIQUE (email);",
    ["ALTER TABLE students ADD UNIQUE (email);", "ALTER TABLE students ADD UNIQUE KEY (email);"],
    "A UNIQUE constraint stops two rows from having the same value.",
    "Use ALTER TABLE students ADD UNIQUE (...).",
  ),
  query(
    "advanced",
    "Advanced",
    3,
    "Add a CHECK constraint named chk_age to students so age must be at least 5.",
    "ALTER TABLE students ADD CONSTRAINT chk_age CHECK (age >= 5);",
    ["ALTER TABLE students ADD CONSTRAINT chk_age CHECK (age >= 5);"],
    "CHECK constraints reject rows that break a rule.",
    "Use ADD CONSTRAINT chk_age CHECK (...).",
  ),
  query(
    "advanced",
    "Advanced",
    4,
    "Set the default value of the city column in students to 'Unknown'.",
    "ALTER TABLE students ALTER COLUMN city SET DEFAULT 'Unknown';",
    [
      "ALTER TABLE students ALTER COLUMN city SET DEFAULT 'Unknown';",
      "ALTER TABLE students MODIFY COLUMN city VARCHAR(100) DEFAULT 'Unknown';",
    ],
    "SET DEFAULT gives a column a value to use when an INSERT leaves it out.",
    "Use ALTER TABLE ... ALTER COLUMN city SET DEFAULT.",
  ),
  query(
    "advanced",
    "Advanced",
    5,
    "Copy every student older than 18 into the adult_students table, which has the same columns.",
    "INSERT INTO adult_students SELECT * FROM students WHERE age > 18;",
    ["INSERT INTO adult_students SELECT * FROM students WHERE age > 18;"],
    "INSERT ... SELECT copies rows from a query straight into another table.",
    "Replace VALUES with a SELECT statement.",
  ),
  query(
    "advanced",
    "Advanced",
    6,
    "Insert a student with id 1, name Asha, and age 18. If id 1 already exists, update the age to 18 instead.",
    "INSERT INTO students (id, name, age) VALUES (1, 'Asha', 18) ON DUPLICATE KEY UPDATE age = 18;",
    [
      "INSERT INTO students (id, name, age) VALUES (1, 'Asha', 18) ON DUPLICATE KEY UPDATE age = 18;",
      "INSERT INTO students (id, name, age) VALUES (1, 'Asha', 18) ON DUPLICATE KEY UPDATE age = VALUES(age);",
    ],
    "ON DUPLICATE KEY UPDATE turns an INSERT into an upsert.",
    "Add ON DUPLICATE KEY UPDATE after the VALUES list.",
  ),
  query(
    "advanced",
    "Advanced",
    7,
    "Set the status of every order to 'vip' when its customer's city is Delhi. Use UPDATE with a JOIN on orders.customer_id = customers.id.",
    "UPDATE orders JOIN customers ON orders.customer_id = customers.id SET orders.status = 'vip' WHERE customers.city = 'Delhi';",
    [
      "UPDATE orders JOIN customers ON orders.customer_id = customers.id SET orders.status = 'vip' WHERE customers.city = 'Delhi';",
      "UPDATE orders o JOIN customers c ON o.customer_id = c.id SET o.status = 'vip' WHERE c.city = 'Delhi';",
    ],
    "MySQL lets UPDATE join other tables so the filter can use their columns.",
    "Write UPDATE ... JOIN ... ON ... SET ... WHERE ....",
  ),
  query(
    "advanced",
    "Advanced",
    8,
    "Delete orders whose customer_id does not exist in the customers table.",
    "DELETE FROM orders WHERE customer_id NOT IN (SELECT id FROM customers);",
    ["DELETE FROM orders WHERE customer_id NOT IN (SELECT id FROM customers);"],
    "A subquery in DELETE's WHERE clause removes orphaned rows.",
    "Use NOT IN (SELECT id FROM customers).",
  ),
  query(
    "advanced",
    "Advanced",
    9,
    "Show each employee's name, salary, and a salary_rank column that ranks them from highest to lowest salary using RANK().",
    "SELECT name, salary, RANK() OVER (ORDER BY salary DESC) AS salary_rank FROM employees;",
    ["SELECT name, salary, RANK() OVER (ORDER BY salary DESC) AS salary_rank FROM employees;"],
    "Window functions like RANK() compute a value across rows without collapsing them.",
    "Use RANK() OVER (ORDER BY salary DESC).",
  ),
  query(
    "advanced",
    "Advanced",
    10,
    "Show each student's name and an age_group column that is 'adult' when age is 18 or more, otherwise 'minor'.",
    "SELECT name, CASE WHEN age >= 18 THEN 'adult' ELSE 'minor' END AS age_group FROM students;",
    [
      "SELECT name, CASE WHEN age >= 18 THEN 'adult' ELSE 'minor' END AS age_group FROM students;",
      "SELECT name, IF(age >= 18, 'adult', 'minor') AS age_group FROM students;",
    ],
    "CASE WHEN ... THEN ... ELSE ... END returns different values based on conditions.",
    "Finish the CASE expression with END, then give it the alias age_group.",
  ),
];

export const MYSQL_COURSE: MysqlCourse = {
  rounds: [
    {
      number: 1,
      title: "Round 1",
      summary: "10 basics questions and 50 query drills across DDL, DML, DCL, TCL, and DQL.",
      topics: ["Basics", "DDL", "DML", "DCL", "TCL", "DQL"],
      steps: ROUND_ONE_STEPS,
    },
    {
      number: 2,
      title: "Round 2",
      summary:
        "10 concept checks and 40 harder query drills across JOINs, subqueries, functions, and advanced MySQL.",
      topics: ["Concepts", "JOINs", "Subqueries", "Functions", "Advanced"],
      steps: ROUND_TWO_STEPS,
    },
  ],
};
