import {type Course, makeMcqBuilder, makeQueryBuilder} from "./course-types";

const basic = makeMcqBuilder("Basics");
const concept = makeMcqBuilder("Concepts");
const query = makeQueryBuilder("sql");

const ROUND_ONE_STEPS = [
  basic(
    1,
    6,
    "Which keyword auto-generates unique integer IDs for a column?",
    ["SERIAL", "AUTO_INCREMENT", "ROWID", "SEQUENCE ONLY"],
    0,
    "SERIAL creates an integer column backed by a sequence that increases automatically.",
    "Think of the PostgreSQL keyword for a self-incrementing column.",
  ),
  basic(
    2,
    6,
    "Which clause lets an INSERT or UPDATE hand back the rows it changed?",
    ["RETURNING", "OUTPUT", "ECHO", "REPLY"],
    0,
    "RETURNING sends back the affected rows right after the statement runs.",
    "It is written at the end of the statement, after the WHERE or VALUES clause.",
  ),
  basic(
    3,
    6,
    "Which type stores JSON with indexing and fast lookups?",
    ["JSONB", "TEXT", "XML", "BYTEA"],
    0,
    "JSONB stores JSON in a binary form that PostgreSQL can index and query efficiently.",
    "Plain JSON is also valid, but this type is optimized for querying.",
  ),
  basic(
    4,
    6,
    "Which command starts the interactive PostgreSQL shell?",
    ["psql", "mysql", "sqlcmd", "redis-cli"],
    0,
    "psql is the standard command-line client for connecting to PostgreSQL.",
    "It shares its first letters with the database's own name.",
  ),
  basic(
    5,
    6,
    "Which property set does PostgreSQL guarantee for transactions?",
    ["ACID", "BASE", "CAP", "REST"],
    0,
    "ACID (atomicity, consistency, isolation, durability) describes PostgreSQL's transaction guarantees.",
    "This is the classic acronym taught for reliable relational transactions.",
  ),
  basic(
    6,
    6,
    "Which clause filters individual rows before any grouping happens?",
    ["WHERE", "HAVING", "GROUP BY", "ORDER BY"],
    0,
    "WHERE removes rows before GROUP BY collects what is left into groups.",
    "HAVING runs after grouping; this clause runs before it.",
  ),
  query(
    "tables",
    "Tables & Data",
    1,
    3,
    "Create a table named products with id as an auto-incrementing primary key, name as TEXT, and price as NUMERIC(10,2).",
    "CREATE TABLE products (id SERIAL PRIMARY KEY, name TEXT, price NUMERIC(10,2));",
    ["CREATE TABLE products (id SERIAL PRIMARY KEY, name TEXT, price NUMERIC(10,2));"],
    "SERIAL is the classic PostgreSQL shorthand for an auto-incrementing integer.",
    "Use SERIAL PRIMARY KEY for id.",
  ),
  query(
    "tables",
    "Tables & Data",
    2,
    3,
    "Insert a product named 'Pen' priced at 2.50 into products, and return its new id.",
    "INSERT INTO products (name, price) VALUES ('Pen', 2.50) RETURNING id;",
    ["INSERT INTO products (name, price) VALUES ('Pen', 2.50) RETURNING id;"],
    "RETURNING hands back column values from the row you just inserted.",
    "Add RETURNING id after the VALUES clause.",
  ),
  query(
    "tables",
    "Tables & Data",
    3,
    3,
    "Add a column named stock of type INT to products.",
    "ALTER TABLE products ADD COLUMN stock INT;",
    ["ALTER TABLE products ADD COLUMN stock INT;"],
    "ALTER TABLE ADD COLUMN extends an existing table with a new column.",
    "Use ALTER TABLE products ADD COLUMN.",
  ),
  query(
    "filtering",
    "Filtering & Sorting",
    1,
    3,
    "Show all products priced over 100, ordered from most to least expensive.",
    "SELECT * FROM products WHERE price > 100 ORDER BY price DESC;",
    ["SELECT * FROM products WHERE price > 100 ORDER BY price DESC;"],
    "WHERE filters the rows, and ORDER BY ... DESC sorts high to low.",
    "Combine WHERE price > 100 with ORDER BY price DESC.",
  ),
  query(
    "filtering",
    "Filtering & Sorting",
    2,
    3,
    "Show only the name and price of products whose stock is less than 10.",
    "SELECT name, price FROM products WHERE stock < 10;",
    ["SELECT name, price FROM products WHERE stock < 10;"],
    "You can select just the columns you need instead of using *.",
    "List name and price, then filter with WHERE stock < 10.",
  ),
  query(
    "filtering",
    "Filtering & Sorting",
    3,
    3,
    "Delete every product whose stock is exactly 0.",
    "DELETE FROM products WHERE stock = 0;",
    ["DELETE FROM products WHERE stock = 0;"],
    "DELETE FROM removes rows that match the WHERE condition.",
    "Filter with WHERE stock = 0.",
  ),
];

const ROUND_TWO_STEPS = [
  concept(
    1,
    6,
    "Which keyword names a temporary result set you can reference later in the same query?",
    ["WITH", "DECLARE", "LOOP", "USING"],
    0,
    "WITH introduces a common table expression (CTE) that the rest of the query can reuse.",
    "It is followed by a name, AS, and a query in parentheses.",
  ),
  concept(
    2,
    6,
    "Which function assigns a rank to each row over an ordered window?",
    ["RANK() OVER (...)", "GROUP BY", "HAVING", "LIMIT"],
    0,
    "Window functions like RANK() compute a value across rows without collapsing them into groups.",
    "Look for the option that pairs a function with OVER.",
  ),
  concept(
    3,
    6,
    "Which clause lets an INSERT update an existing row instead of failing on a duplicate key?",
    ["ON CONFLICT", "ON DUPLICATE", "ON ERROR", "TRY CATCH"],
    0,
    "ON CONFLICT ... DO UPDATE turns an INSERT into an upsert.",
    "It is written right after the VALUES list.",
  ),
  concept(
    4,
    6,
    "Which operator pulls a JSONB field out as plain text?",
    ["->>", "::", "|>", "@>"],
    0,
    "The ->> operator extracts a JSON field and returns it as text.",
    "The single-arrow version returns JSON; this one returns text.",
  ),
  concept(
    5,
    6,
    "Which extension adds fast fuzzy text search using trigrams?",
    ["pg_trgm", "hstore", "postgis", "uuid-ossp"],
    0,
    "pg_trgm indexes text by trigrams, which speeds up LIKE and similarity searches.",
    "Its name is short for trigram.",
  ),
  concept(
    6,
    6,
    "Which keyword checks whether a value equals any element in an array column?",
    ["ANY", "ALL", "ONLY", "EVERY"],
    0,
    "= ANY(array_column) checks whether the value matches at least one array element.",
    "The opposite check across every element uses ALL instead.",
  ),
  query(
    "window",
    "Window & CTE",
    1,
    3,
    "Using a CTE named high_value that holds products priced over 100, select everything from high_value.",
    "WITH high_value AS (SELECT * FROM products WHERE price > 100) SELECT * FROM high_value;",
    ["WITH high_value AS (SELECT * FROM products WHERE price > 100) SELECT * FROM high_value;"],
    "A CTE names a subquery so the rest of the statement can read more clearly.",
    "Start with WITH high_value AS ( ... ).",
  ),
  query(
    "window",
    "Window & CTE",
    2,
    3,
    "Show each product's name, price, and a price_rank column ranking them from highest to lowest price.",
    "SELECT name, price, RANK() OVER (ORDER BY price DESC) AS price_rank FROM products;",
    ["SELECT name, price, RANK() OVER (ORDER BY price DESC) AS price_rank FROM products;"],
    "RANK() OVER (ORDER BY ...) numbers rows without collapsing them.",
    "Add RANK() OVER (ORDER BY price DESC) AS price_rank to the SELECT list.",
  ),
  query(
    "window",
    "Window & CTE",
    3,
    3,
    "Show each product's id and a running total of stock, ordered by id.",
    "SELECT id, SUM(stock) OVER (ORDER BY id) FROM products;",
    ["SELECT id, SUM(stock) OVER (ORDER BY id) FROM products;"],
    "SUM() OVER (ORDER BY ...) adds up values as it moves through the ordered rows.",
    "Use SUM(stock) OVER (ORDER BY id).",
  ),
  query(
    "jsonb",
    "JSONB & Upserts",
    1,
    3,
    "Insert a product with id 1 and name 'Pen'. If id 1 already exists, update its name instead.",
    "INSERT INTO products (id, name) VALUES (1, 'Pen') ON CONFLICT (id) DO UPDATE SET name = 'Pen';",
    ["INSERT INTO products (id, name) VALUES (1, 'Pen') ON CONFLICT (id) DO UPDATE SET name = 'Pen';"],
    "ON CONFLICT (id) DO UPDATE turns the INSERT into an upsert keyed on id.",
    "Add ON CONFLICT (id) DO UPDATE SET name = 'Pen' after the VALUES list.",
  ),
  query(
    "jsonb",
    "JSONB & Upserts",
    2,
    3,
    "Add a metadata column of type JSONB to products.",
    "ALTER TABLE products ADD COLUMN metadata JSONB;",
    ["ALTER TABLE products ADD COLUMN metadata JSONB;"],
    "JSONB columns can hold flexible, queryable JSON documents inside a relational table.",
    "Use ALTER TABLE products ADD COLUMN metadata JSONB.",
  ),
  query(
    "jsonb",
    "JSONB & Upserts",
    3,
    3,
    "Show the 'color' field from each product's metadata JSONB column, as text.",
    "SELECT metadata ->> 'color' FROM products;",
    ["SELECT metadata ->> 'color' FROM products;"],
    "The ->> operator reads a JSONB field out as text.",
    "Use metadata ->> 'color' in the SELECT list.",
  ),
];

export const POSTGRESQL_COURSE: Course = {
  rounds: [
    {
      number: 1,
      title: "Round 1",
      summary: "6 basics questions and 6 query drills covering tables, inserts, and filtering.",
      topics: ["Basics", "Tables & Data", "Filtering & Sorting"],
      steps: ROUND_ONE_STEPS,
    },
    {
      number: 2,
      title: "Round 2",
      summary: "6 concept checks and 6 harder query drills covering CTEs, window functions, and JSONB.",
      topics: ["Concepts", "Window & CTE", "JSONB & Upserts"],
      steps: ROUND_TWO_STEPS,
    },
  ],
};
