import {type Course, makeMcqBuilder, makeQueryBuilder} from "./course-types";

const basic = makeMcqBuilder("Basics");
const concept = makeMcqBuilder("Concepts");
const query = makeQueryBuilder("sql");

const ROUND_ONE_STEPS = [
  basic(
    1,
    6,
    "Where does Redis primarily keep its data?",
    ["In memory", "On a spinning disk only", "In a browser cache", "In a distributed file system"],
    0,
    "Redis keeps data in memory, which is what makes it so fast.",
    "Think about what makes Redis reads and writes so quick.",
  ),
  basic(
    2,
    6,
    "What is Redis's basic data model?",
    ["Key-value", "Wide-column", "Document", "Graph"],
    0,
    "Every piece of data in Redis is stored under a key.",
    "It is the simplest data model on this list.",
  ),
  basic(
    3,
    6,
    "How many threads does the classic Redis command loop use to execute commands?",
    ["One", "Four", "Sixteen", "One per core"],
    0,
    "Redis executes commands one at a time on a single thread, which keeps it simple and predictable.",
    "This is why individual commands never race each other inside Redis.",
  ),
  basic(
    4,
    6,
    "Which file format lets Redis save a point-in-time snapshot to disk?",
    ["RDB", "AOF", "WAL", "BSON"],
    0,
    "RDB snapshots save the whole dataset to disk at set intervals.",
    "The other persistence option logs every write instead.",
  ),
  basic(
    5,
    6,
    "Which command checks whether a key exists?",
    ["EXISTS", "HAS", "CONTAINS", "FIND"],
    0,
    "EXISTS returns how many of the given keys are present.",
    "It is a direct, one-word command name.",
  ),
  basic(
    6,
    6,
    "Which command removes a key?",
    ["DEL", "REMOVE", "DROP", "CLEAR"],
    0,
    "DEL deletes one or more keys immediately.",
    "It is a short, four-letter command.",
  ),
  query(
    "strings",
    "Strings & Keys",
    1,
    3,
    "Set the key name to the value Asha.",
    "SET name Asha",
    ["SET name Asha"],
    "SET stores a value under a key, overwriting whatever was there before.",
    "Use SET followed by the key and the value.",
  ),
  query(
    "strings",
    "Strings & Keys",
    2,
    3,
    "Get the value stored at the key name.",
    "GET name",
    ["GET name"],
    "GET reads back the string value stored at a key.",
    "Use GET followed by the key.",
  ),
  query(
    "strings",
    "Strings & Keys",
    3,
    3,
    "Increase the value stored at the key counter by 1.",
    "INCR counter",
    ["INCR counter"],
    "INCR treats the stored value as a number and adds one to it atomically.",
    "Use INCR followed by the key.",
  ),
  query(
    "expiry",
    "Expiry",
    1,
    3,
    "Delete the key named session.",
    "DEL session",
    ["DEL session"],
    "DEL removes a key and its value entirely.",
    "Use DEL followed by the key.",
  ),
  query(
    "expiry",
    "Expiry",
    2,
    3,
    "Make the key session expire in 30 seconds.",
    "EXPIRE session 30",
    ["EXPIRE session 30"],
    "EXPIRE sets a countdown, in seconds, after which the key is removed automatically.",
    "Use EXPIRE followed by the key and the number of seconds.",
  ),
  query(
    "expiry",
    "Expiry",
    3,
    3,
    "Check how many seconds remain before the key session expires.",
    "TTL session",
    ["TTL session"],
    "TTL returns the remaining time to live for a key, in seconds.",
    "Use TTL followed by the key.",
  ),
];

const ROUND_TWO_STEPS = [
  concept(
    1,
    6,
    "Which Redis structure keeps ordered elements you can push to either end?",
    ["List", "Set", "Hash", "Sorted set"],
    0,
    "A Redis list is an ordered sequence you can push and pop from both ends.",
    "Think of it like a deque of values.",
  ),
  concept(
    2,
    6,
    "Which Redis structure stores unique unordered members?",
    ["Set", "List", "Hash", "Stream"],
    0,
    "A set automatically keeps every member unique, with no guaranteed order.",
    "This is the same idea as a mathematical set.",
  ),
  concept(
    3,
    6,
    "Which Redis structure stores field-value pairs under one key, like a small object?",
    ["Hash", "Set", "List", "Sorted set"],
    0,
    "A hash groups several fields under one key, similar to a small record.",
    "Think of it as a mini object stored at a single key.",
  ),
  concept(
    4,
    6,
    "Which Redis structure keeps unique members ordered by a score?",
    ["Sorted set", "Set", "List", "Hash"],
    0,
    "A sorted set (ZSET) keeps members unique but ranked by a numeric score.",
    "It is often used for leaderboards.",
  ),
  concept(
    5,
    6,
    "Which messaging pattern lets clients subscribe to channels and receive published messages?",
    ["Pub/Sub", "Batching", "Polling", "Sharding"],
    0,
    "Publish/subscribe lets one client broadcast a message to every subscriber of a channel.",
    "The name is short for publish and subscribe.",
  ),
  concept(
    6,
    6,
    "Which append-only log format trades some speed for better durability than snapshots?",
    ["AOF", "RDB", "WAL only", "BSON"],
    0,
    "The append-only file logs every write, so less data is lost if Redis stops unexpectedly.",
    "Its name describes a file that is only ever appended to.",
  ),
  query(
    "structures",
    "Structures",
    1,
    3,
    "Push the value 'task1' onto the left of the list named queue.",
    "LPUSH queue task1",
    ["LPUSH queue task1"],
    "LPUSH adds a new element to the left (head) of a list.",
    "Use LPUSH followed by the list key and the value.",
  ),
  query(
    "structures",
    "Structures",
    2,
    3,
    "Set the field name to Asha in the hash named user:1.",
    "HSET user:1 name Asha",
    ["HSET user:1 name Asha"],
    "HSET writes one field inside a hash stored at the given key.",
    "Use HSET followed by the hash key, field, and value.",
  ),
  query(
    "structures",
    "Structures",
    3,
    3,
    "Add the member 'sql' to the set named tags.",
    "SADD tags sql",
    ["SADD tags sql"],
    "SADD adds one or more members to a set, ignoring duplicates.",
    "Use SADD followed by the set key and the member.",
  ),
  query(
    "pubsub",
    "Pub/Sub",
    1,
    3,
    "Add 'Asha' to the sorted set leaderboard with a score of 100.",
    "ZADD leaderboard 100 Asha",
    ["ZADD leaderboard 100 Asha"],
    "ZADD takes a score before each member it adds to a sorted set.",
    "Use ZADD followed by the key, the score, then the member.",
  ),
  query(
    "pubsub",
    "Pub/Sub",
    2,
    3,
    "Subscribe to the channel named updates.",
    "SUBSCRIBE updates",
    ["SUBSCRIBE updates"],
    "SUBSCRIBE listens on one or more channels for published messages.",
    "Use SUBSCRIBE followed by the channel name.",
  ),
  query(
    "pubsub",
    "Pub/Sub",
    3,
    3,
    "Publish the message 'hello' to the channel named updates.",
    "PUBLISH updates hello",
    ["PUBLISH updates hello"],
    "PUBLISH sends a message to every current subscriber of a channel.",
    "Use PUBLISH followed by the channel name and the message.",
  ),
];

export const REDIS_COURSE: Course = {
  rounds: [
    {
      number: 1,
      title: "Round 1",
      summary: "6 basics questions and 6 command drills covering strings, keys, and expiry.",
      topics: ["Basics", "Strings & Keys", "Expiry"],
      steps: ROUND_ONE_STEPS,
    },
    {
      number: 2,
      title: "Round 2",
      summary: "6 concept checks and 6 harder command drills covering data structures and pub/sub.",
      topics: ["Concepts", "Structures", "Pub/Sub"],
      steps: ROUND_TWO_STEPS,
    },
  ],
};
