import {type Course, makeMcqBuilder, makeQueryBuilder} from "./course-types";

const basic = makeMcqBuilder("Basics");
const concept = makeMcqBuilder("Concepts");
const query = makeQueryBuilder("sql");

const ROUND_ONE_STEPS = [
  basic(
    1,
    6,
    "How is a SQLite database usually stored?",
    ["As a single file", "On a dedicated server", "In browser memory only", "Across many nodes"],
    0,
    "SQLite keeps an entire database in one ordinary file on disk.",
    "Think about what makes SQLite easy to copy and ship.",
  ),
  basic(
    2,
    6,
    "Which command shows a table's column info in the sqlite3 CLI?",
    ["PRAGMA table_info", "DESCRIBE", "SHOW COLUMNS", "EXPLAIN TABLE"],
    0,
    "PRAGMA table_info(table_name) lists each column's name, type, and constraints.",
    "SQLite exposes many settings and metadata through PRAGMA statements.",
  ),
  basic(
    3,
    6,
    "Which keyword makes an INTEGER PRIMARY KEY column auto-increment its rowid?",
    ["AUTOINCREMENT", "SERIAL", "IDENTITY", "SEQUENCE"],
    0,
    "AUTOINCREMENT guarantees rowids always increase and are never reused.",
    "Without it, SQLite may still reuse rowids from deleted rows.",
  ),
  basic(
    4,
    6,
    "SQLite is best described as which kind of database?",
    ["Embedded / serverless", "Distributed cluster", "In-memory cache only", "Document store"],
    0,
    "SQLite runs inside your application; there is no separate server process to manage.",
    "Think about what 'embedded' means for a database.",
  ),
  basic(
    5,
    6,
    "Which statement inserts a row, replacing any existing row with the same primary key?",
    ["INSERT OR REPLACE", "INSERT DUPLICATE", "MERGE INTO", "UPSERT ONLY"],
    0,
    "INSERT OR REPLACE deletes the conflicting row first, then inserts the new one.",
    "The clause is written right after INSERT.",
  ),
  basic(
    6,
    6,
    "Which type affinity does SQLite use for most character data?",
    ["TEXT", "VARCHAR2", "NVARCHAR", "STRING"],
    0,
    "SQLite uses flexible type affinities, and TEXT is the one for character data.",
    "It is the simplest, most direct name for text.",
  ),
  query(
    "tables",
    "Tables & Data",
    1,
    3,
    "Create a table named notes with id as an auto-incrementing integer primary key, and body as TEXT.",
    "CREATE TABLE notes (id INTEGER PRIMARY KEY AUTOINCREMENT, body TEXT);",
    ["CREATE TABLE notes (id INTEGER PRIMARY KEY AUTOINCREMENT, body TEXT);"],
    "INTEGER PRIMARY KEY AUTOINCREMENT guarantees ever-increasing, never-reused ids.",
    "Use INTEGER PRIMARY KEY AUTOINCREMENT for id.",
  ),
  query(
    "tables",
    "Tables & Data",
    2,
    3,
    "Insert a note with the body 'Buy milk'.",
    "INSERT INTO notes (body) VALUES ('Buy milk');",
    ["INSERT INTO notes (body) VALUES ('Buy milk');"],
    "id is left out of the column list so SQLite assigns it automatically.",
    "Use INSERT INTO notes (body) VALUES (...).",
  ),
  query(
    "tables",
    "Tables & Data",
    3,
    3,
    "Add a column named done of type INTEGER, defaulting to 0, to notes.",
    "ALTER TABLE notes ADD COLUMN done INTEGER DEFAULT 0;",
    ["ALTER TABLE notes ADD COLUMN done INTEGER DEFAULT 0;"],
    "ALTER TABLE ADD COLUMN can also set a default value for existing rows.",
    "Use ALTER TABLE notes ADD COLUMN done INTEGER DEFAULT 0.",
  ),
  query(
    "filtering",
    "Filtering",
    1,
    3,
    "Show all notes that are not done (done equals 0).",
    "SELECT * FROM notes WHERE done = 0;",
    ["SELECT * FROM notes WHERE done = 0;"],
    "WHERE done = 0 keeps only the notes that are not finished yet.",
    "Filter with WHERE done = 0.",
  ),
  query(
    "filtering",
    "Filtering",
    2,
    3,
    "Show the 5 most recently added notes, using id descending.",
    "SELECT * FROM notes ORDER BY id DESC LIMIT 5;",
    ["SELECT * FROM notes ORDER BY id DESC LIMIT 5;"],
    "Sorting by id descending puts the newest rows first, then LIMIT caps the count.",
    "Use ORDER BY id DESC LIMIT 5.",
  ),
  query(
    "filtering",
    "Filtering",
    3,
    3,
    "Mark the note with id 1 as done.",
    "UPDATE notes SET done = 1 WHERE id = 1;",
    ["UPDATE notes SET done = 1 WHERE id = 1;"],
    "UPDATE ... SET ... WHERE changes only the matching row.",
    "Target the row with WHERE id = 1.",
  ),
];

const ROUND_TWO_STEPS = [
  concept(
    1,
    6,
    "Which clause makes an INSERT update an existing row instead of failing on a duplicate key?",
    ["ON CONFLICT DO UPDATE", "ON DUPLICATE KEY", "DROP AND RECREATE", "MERGE INTO"],
    0,
    "ON CONFLICT (column) DO UPDATE performs a true upsert, keeping the original rowid.",
    "This is different from INSERT OR REPLACE, which deletes and re-inserts the row.",
  ),
  concept(
    2,
    6,
    "Which pragma turns on enforcement of FOREIGN KEY constraints for a connection?",
    ["PRAGMA foreign_keys = ON", "PRAGMA strict = ON", "SET FOREIGN_KEY_CHECKS=1", "ENABLE FOREIGN KEYS"],
    0,
    "SQLite does not enforce foreign keys by default; this pragma turns it on per connection.",
    "It is written as a PRAGMA statement, not a SET statement.",
  ),
  concept(
    3,
    6,
    "Which journal mode allows concurrent readers alongside one writer?",
    ["WAL", "DELETE", "MEMORY", "OFF"],
    0,
    "Write-Ahead Logging (WAL) mode lets reads continue while a write is in progress.",
    "The name is an abbreviation you can say as one word.",
  ),
  concept(
    4,
    6,
    "Which command attaches a second database file to the current connection?",
    ["ATTACH DATABASE", "LINK DATABASE", "IMPORT DATABASE", "MOUNT DATABASE"],
    0,
    "ATTACH DATABASE lets you query across more than one SQLite file at once.",
    "It is followed by a file path and an AS alias.",
  ),
  concept(
    5,
    6,
    "Which keyword combines two SELECT results and removes duplicate rows?",
    ["UNION", "UNION ALL", "JOIN", "MERGE"],
    0,
    "UNION stacks two result sets and removes duplicates; UNION ALL keeps them.",
    "The plain version, without ALL, is the one that removes duplicates.",
  ),
  concept(
    6,
    6,
    "Which clause filters grouped rows after aggregation runs?",
    ["HAVING", "WHERE", "ORDER BY", "LIMIT"],
    0,
    "HAVING runs after GROUP BY, so it can filter on aggregate results like COUNT(*).",
    "WHERE cannot see aggregate results because it runs earlier.",
  ),
  query(
    "upserts",
    "Upserts & Pragmas",
    1,
    3,
    "Insert a note with id 1 and body 'Buy milk'. If id 1 already exists, update its body instead.",
    "INSERT INTO notes (id, body) VALUES (1, 'Buy milk') ON CONFLICT (id) DO UPDATE SET body = 'Buy milk';",
    ["INSERT INTO notes (id, body) VALUES (1, 'Buy milk') ON CONFLICT (id) DO UPDATE SET body = 'Buy milk';"],
    "ON CONFLICT (id) DO UPDATE keeps the same rowid instead of deleting and re-inserting.",
    "Add ON CONFLICT (id) DO UPDATE SET body = 'Buy milk' after the VALUES list.",
  ),
  query(
    "upserts",
    "Upserts & Pragmas",
    2,
    3,
    "Turn on foreign key constraint enforcement for this connection.",
    "PRAGMA foreign_keys = ON;",
    ["PRAGMA foreign_keys = ON;"],
    "This pragma must be run on every new connection since SQLite does not persist it.",
    "Use PRAGMA foreign_keys = ON.",
  ),
  query(
    "upserts",
    "Upserts & Pragmas",
    3,
    3,
    "Show the column info for the notes table.",
    "PRAGMA table_info(notes);",
    ["PRAGMA table_info(notes);"],
    "PRAGMA table_info returns one row per column, including its name and type.",
    "Use PRAGMA table_info(notes).",
  ),
  query(
    "joins",
    "Joins & Subqueries",
    1,
    3,
    "Create a table named tags with id as an auto-incrementing integer primary key, note_id INTEGER, and label TEXT, with a foreign key from note_id to notes(id).",
    "CREATE TABLE tags (id INTEGER PRIMARY KEY AUTOINCREMENT, note_id INTEGER, label TEXT, FOREIGN KEY (note_id) REFERENCES notes(id));",
    ["CREATE TABLE tags (id INTEGER PRIMARY KEY AUTOINCREMENT, note_id INTEGER, label TEXT, FOREIGN KEY (note_id) REFERENCES notes(id));"],
    "FOREIGN KEY ... REFERENCES links tags back to the notes table.",
    "Add FOREIGN KEY (note_id) REFERENCES notes(id) after the columns.",
  ),
  query(
    "joins",
    "Joins & Subqueries",
    2,
    3,
    "Show each note's body with its tag label, joining notes and tags where notes.id matches tags.note_id.",
    "SELECT notes.body, tags.label FROM notes JOIN tags ON notes.id = tags.note_id;",
    [
      "SELECT notes.body, tags.label FROM notes JOIN tags ON notes.id = tags.note_id;",
      "SELECT n.body, t.label FROM notes n JOIN tags t ON n.id = t.note_id;",
    ],
    "A JOIN combines rows from two tables that share a matching value.",
    "Use JOIN tags ON notes.id = tags.note_id.",
  ),
  query(
    "joins",
    "Joins & Subqueries",
    3,
    3,
    "Show notes that have no tags, using a subquery with NOT IN.",
    "SELECT * FROM notes WHERE id NOT IN (SELECT note_id FROM tags);",
    ["SELECT * FROM notes WHERE id NOT IN (SELECT note_id FROM tags);"],
    "NOT IN with a subquery keeps rows whose id never appears in the other table.",
    "Compare notes.id against (SELECT note_id FROM tags) using NOT IN.",
  ),
];

export const SQLITE_COURSE: Course = {
  rounds: [
    {
      number: 1,
      title: "Round 1",
      summary: "6 basics questions and 6 query drills covering tables, inserts, and filtering.",
      topics: ["Basics", "Tables & Data", "Filtering"],
      steps: ROUND_ONE_STEPS,
    },
    {
      number: 2,
      title: "Round 2",
      summary: "6 concept checks and 6 harder query drills covering upserts, pragmas, joins, and subqueries.",
      topics: ["Concepts", "Upserts & Pragmas", "Joins & Subqueries"],
      steps: ROUND_TWO_STEPS,
    },
  ],
};
