import {type Course, makeMcqBuilder, makeQueryBuilder} from "./course-types";

const basic = makeMcqBuilder("Basics");
const concept = makeMcqBuilder("Concepts");
const query = makeQueryBuilder("sql");

const ROUND_ONE_STEPS = [
  basic(
    1,
    6,
    "Which keyword limits how many rows come back, written before the column list?",
    ["TOP", "LIMIT", "FETCH", "ROWNUM"],
    0,
    "SQL Server uses TOP right after SELECT to cap the number of rows returned.",
    "It reads naturally: SELECT TOP 5 ...",
  ),
  basic(
    2,
    6,
    "Which property makes a column auto-generate increasing row numbers?",
    ["IDENTITY", "SERIAL", "AUTO_INCREMENT", "SEQUENCE ONLY"],
    0,
    "IDENTITY marks a column as self-incrementing, commonly used for primary keys.",
    "This is SQL Server's own keyword for the feature.",
  ),
  basic(
    3,
    6,
    "What is Microsoft's own SQL dialect called?",
    ["T-SQL", "PL/SQL", "MySQL", "NoSQL"],
    0,
    "T-SQL (Transact-SQL) is Microsoft's extension of standard SQL used in SQL Server.",
    "The answer starts with a T.",
  ),
  basic(
    4,
    6,
    "Which tool is the standard GUI for managing SQL Server?",
    ["SSMS", "phpMyAdmin", "pgAdmin", "MongoDB Compass"],
    0,
    "SSMS stands for SQL Server Management Studio.",
    "Look for the Microsoft-branded management tool.",
  ),
  basic(
    5,
    6,
    "Which keyword separates batches of statements in an SSMS script?",
    ["GO", "END", "COMMIT", "RUN"],
    0,
    "GO tells SSMS to send everything above it as one batch before moving on.",
    "It is a short, all-caps word on its own line.",
  ),
  basic(
    6,
    6,
    "Which system database stores SQL Server login and configuration information?",
    ["master", "msdb", "tempdb", "model"],
    0,
    "The master database holds server-wide system information, including logins.",
    "Think of the database every SQL Server instance depends on to start up.",
  ),
  query(
    "tables",
    "Tables & Data",
    1,
    3,
    "Create a table named employees with id as an auto-incrementing primary key, name as NVARCHAR(100), and salary as DECIMAL(10,2).",
    "CREATE TABLE employees (id INT IDENTITY PRIMARY KEY, name NVARCHAR(100), salary DECIMAL(10,2));",
    ["CREATE TABLE employees (id INT IDENTITY PRIMARY KEY, name NVARCHAR(100), salary DECIMAL(10,2));"],
    "IDENTITY makes an INT column auto-increment, similar to AUTO_INCREMENT in other databases.",
    "Use INT IDENTITY PRIMARY KEY for id.",
  ),
  query(
    "tables",
    "Tables & Data",
    2,
    3,
    "Insert an employee named 'Asha' with a salary of 50000.",
    "INSERT INTO employees (name, salary) VALUES ('Asha', 50000);",
    ["INSERT INTO employees (name, salary) VALUES ('Asha', 50000);"],
    "INSERT INTO works the same way in T-SQL as in standard SQL.",
    "List the columns, then VALUES with the matching data.",
  ),
  query(
    "tables",
    "Tables & Data",
    3,
    3,
    "Add a column named department to employees, as NVARCHAR(50).",
    "ALTER TABLE employees ADD department NVARCHAR(50);",
    ["ALTER TABLE employees ADD department NVARCHAR(50);", "ALTER TABLE employees ADD COLUMN department NVARCHAR(50);"],
    "T-SQL allows ALTER TABLE ... ADD without the word COLUMN.",
    "Use ALTER TABLE employees ADD.",
  ),
  query(
    "filtering",
    "Filtering",
    1,
    3,
    "Show the 5 highest paid employees.",
    "SELECT TOP 5 * FROM employees ORDER BY salary DESC;",
    ["SELECT TOP 5 * FROM employees ORDER BY salary DESC;"],
    "TOP goes right after SELECT, before the column list.",
    "Use SELECT TOP 5 * FROM employees ORDER BY salary DESC.",
  ),
  query(
    "filtering",
    "Filtering",
    2,
    3,
    "Show employees whose name starts with A.",
    "SELECT * FROM employees WHERE name LIKE 'A%';",
    ["SELECT * FROM employees WHERE name LIKE 'A%';"],
    "LIKE with a percent sign matches text patterns.",
    "Use LIKE 'A%'.",
  ),
  query(
    "filtering",
    "Filtering",
    3,
    3,
    "Update the salary of the employee named Asha to 55000.",
    "UPDATE employees SET salary = 55000 WHERE name = 'Asha';",
    ["UPDATE employees SET salary = 55000 WHERE name = 'Asha';"],
    "UPDATE ... SET ... WHERE changes matching rows.",
    "Target the row with WHERE name = 'Asha'.",
  ),
];

const ROUND_TWO_STEPS = [
  concept(
    1,
    6,
    "Which clause pair replaces TOP when you need to skip rows first?",
    ["OFFSET ... FETCH NEXT", "LIMIT ... SKIP", "TOP ... SKIP", "ROWNUM BETWEEN"],
    0,
    "OFFSET skips a number of rows, and FETCH NEXT takes the rows after that point.",
    "Both keywords are needed together, usually after ORDER BY.",
  ),
  concept(
    2,
    6,
    "Which statement can INSERT, UPDATE, and DELETE in one pass based on a match?",
    ["MERGE", "UPSERT", "SYNC", "COMBINE"],
    0,
    "MERGE compares a source and target table and applies matched or unmatched actions.",
    "Its name suggests combining two datasets.",
  ),
  concept(
    3,
    6,
    "Which window function numbers rows with no ties or gaps?",
    ["ROW_NUMBER()", "RANK()", "DENSE_RANK()", "NTILE()"],
    0,
    "ROW_NUMBER() always gives each row a unique, sequential number.",
    "The other options can repeat or skip numbers when values tie.",
  ),
  concept(
    4,
    6,
    "Which keyword defines a temporary named result set for a single statement?",
    ["WITH", "DECLARE", "TEMP", "USING"],
    0,
    "WITH introduces a common table expression, just like in standard SQL.",
    "It is followed by a name, AS, and a query.",
  ),
  concept(
    5,
    6,
    "Which function converts a value and returns NULL instead of erroring on failure?",
    ["TRY_CONVERT", "CAST", "CONVERT", "PARSE"],
    0,
    "TRY_CONVERT is the safe version of CONVERT for uncertain input.",
    "Its name starts with TRY_.",
  ),
  concept(
    6,
    6,
    "Which clause is required right after OFFSET to actually return rows?",
    ["FETCH NEXT", "TOP", "LIMIT", "TAKE"],
    0,
    "OFFSET alone only skips rows; FETCH NEXT specifies how many to return after that.",
    "It comes right after the OFFSET ... ROWS clause.",
  ),
  query(
    "paging",
    "Paging & Ranking",
    1,
    3,
    "Show employees 6 through 10 when ordered by salary descending, using OFFSET and FETCH.",
    "SELECT * FROM employees ORDER BY salary DESC OFFSET 5 ROWS FETCH NEXT 5 ROWS ONLY;",
    ["SELECT * FROM employees ORDER BY salary DESC OFFSET 5 ROWS FETCH NEXT 5 ROWS ONLY;"],
    "OFFSET 5 ROWS skips the first 5, and FETCH NEXT 5 ROWS ONLY takes the next 5.",
    "Order first, then add OFFSET ... FETCH NEXT ... ROWS ONLY.",
  ),
  query(
    "paging",
    "Paging & Ranking",
    2,
    3,
    "Show each employee's name, salary, and a salary_rank column numbering them from highest to lowest salary with no gaps, using ROW_NUMBER().",
    "SELECT name, salary, ROW_NUMBER() OVER (ORDER BY salary DESC) AS salary_rank FROM employees;",
    ["SELECT name, salary, ROW_NUMBER() OVER (ORDER BY salary DESC) AS salary_rank FROM employees;"],
    "ROW_NUMBER() OVER (ORDER BY ...) assigns a unique running number to each row.",
    "Add ROW_NUMBER() OVER (ORDER BY salary DESC) AS salary_rank.",
  ),
  query(
    "paging",
    "Paging & Ranking",
    3,
    3,
    "Show each department with its average salary.",
    "SELECT department, AVG(salary) FROM employees GROUP BY department;",
    ["SELECT department, AVG(salary) FROM employees GROUP BY department;"],
    "AVG() together with GROUP BY summarizes salaries per department.",
    "Group by department and use AVG(salary).",
  ),
  query(
    "merge",
    "Merge & CTE",
    1,
    3,
    "Using a CTE named senior that holds employees with salary over 60000, select everything from senior.",
    "WITH senior AS (SELECT * FROM employees WHERE salary > 60000) SELECT * FROM senior;",
    ["WITH senior AS (SELECT * FROM employees WHERE salary > 60000) SELECT * FROM senior;"],
    "A CTE gives a subquery a name you can select from afterward.",
    "Start with WITH senior AS ( ... ).",
  ),
  query(
    "merge",
    "Merge & CTE",
    2,
    3,
    "Using MERGE, update employee id 1's name to 'Asha' if a row with id 1 exists in employees, or insert it if it does not. Use a source of (SELECT 1 AS id, 'Asha' AS name) AS src matched on employees.id = src.id.",
    "MERGE employees AS target USING (SELECT 1 AS id, 'Asha' AS name) AS src ON target.id = src.id WHEN MATCHED THEN UPDATE SET name = src.name WHEN NOT MATCHED THEN INSERT (id, name) VALUES (src.id, src.name);",
    [
      "MERGE employees AS target USING (SELECT 1 AS id, 'Asha' AS name) AS src ON target.id = src.id WHEN MATCHED THEN UPDATE SET name = src.name WHEN NOT MATCHED THEN INSERT (id, name) VALUES (src.id, src.name);",
      "MERGE INTO employees AS target USING (SELECT 1 AS id, 'Asha' AS name) AS src ON target.id = src.id WHEN MATCHED THEN UPDATE SET name = src.name WHEN NOT MATCHED THEN INSERT (id, name) VALUES (src.id, src.name);",
    ],
    "MERGE lets one statement update matched rows and insert unmatched ones.",
    "Write MERGE employees AS target USING (...) AS src ON ..., then WHEN MATCHED and WHEN NOT MATCHED.",
  ),
  query(
    "merge",
    "Merge & CTE",
    3,
    3,
    "Delete employees whose department is NULL.",
    "DELETE FROM employees WHERE department IS NULL;",
    ["DELETE FROM employees WHERE department IS NULL;"],
    "IS NULL is required to test for missing values; = NULL never matches.",
    "Use WHERE department IS NULL.",
  ),
];

export const SQLSERVER_COURSE: Course = {
  rounds: [
    {
      number: 1,
      title: "Round 1",
      summary: "6 basics questions and 6 query drills covering tables, TOP, and filtering.",
      topics: ["Basics", "Tables & Data", "Filtering"],
      steps: ROUND_ONE_STEPS,
    },
    {
      number: 2,
      title: "Round 2",
      summary: "6 concept checks and 6 harder query drills covering paging, ranking, MERGE, and CTEs.",
      topics: ["Concepts", "Paging & Ranking", "Merge & CTE"],
      steps: ROUND_TWO_STEPS,
    },
  ],
};
